//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Summer.CompetitiveTender.Service.ServiceReferenceGpEvalResult {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservice.govpurchase.opensource.com/", ConfigurationName="ServiceReferenceGpEvalResult.GpEvalResultWebService")]
    public interface GpEvalResultWebService {
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(saveResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(save))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseEntity))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Summer.CompetitiveTender.Service.ServiceReferenceGpEvalResult.saveResponse1 save(Summer.CompetitiveTender.Service.ServiceReferenceGpEvalResult.save1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.govpurchase.opensource.com/")]
    public partial class gpEvalResultWebDO : baseEntity {
        
        private string gadBidCompanyIdField;
        
        private string gadBidCompanyNameField;
        
        private string gadBidPersonIdField;
        
        private string gadIdField;
        
        private string gerCodeField;
        
        private string gerCompanyIdField;
        
        private string gerIdField;
        
        private string gerPersonIdField;
        
        private int gerResultField;
        
        private bool gerResultFieldSpecified;
        
        private double gerScoresField;
        
        private bool gerScoresFieldSpecified;
        
        private System.DateTime gerTimeField;
        
        private bool gerTimeFieldSpecified;
        
        private long gewtIdField;
        
        private bool gewtIdFieldSpecified;
        
        private string gsIdField;
        
        private string gsewiIdField;
        
        private string gsewiNameField;
        
        private string gtpIdField;
        
        private string optCoIdField;
        
        private string optIdField;
        
        private System.DateTime optTimeField;
        
        private bool optTimeFieldSpecified;
        
        private string remarkField;
        
        private int stateField;
        
        private bool stateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string gadBidCompanyId {
            get {
                return this.gadBidCompanyIdField;
            }
            set {
                this.gadBidCompanyIdField = value;
                this.RaisePropertyChanged("gadBidCompanyId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string gadBidCompanyName {
            get {
                return this.gadBidCompanyNameField;
            }
            set {
                this.gadBidCompanyNameField = value;
                this.RaisePropertyChanged("gadBidCompanyName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string gadBidPersonId {
            get {
                return this.gadBidPersonIdField;
            }
            set {
                this.gadBidPersonIdField = value;
                this.RaisePropertyChanged("gadBidPersonId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string gadId {
            get {
                return this.gadIdField;
            }
            set {
                this.gadIdField = value;
                this.RaisePropertyChanged("gadId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string gerCode {
            get {
                return this.gerCodeField;
            }
            set {
                this.gerCodeField = value;
                this.RaisePropertyChanged("gerCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string gerCompanyId {
            get {
                return this.gerCompanyIdField;
            }
            set {
                this.gerCompanyIdField = value;
                this.RaisePropertyChanged("gerCompanyId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string gerId {
            get {
                return this.gerIdField;
            }
            set {
                this.gerIdField = value;
                this.RaisePropertyChanged("gerId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string gerPersonId {
            get {
                return this.gerPersonIdField;
            }
            set {
                this.gerPersonIdField = value;
                this.RaisePropertyChanged("gerPersonId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public int gerResult {
            get {
                return this.gerResultField;
            }
            set {
                this.gerResultField = value;
                this.RaisePropertyChanged("gerResult");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool gerResultSpecified {
            get {
                return this.gerResultFieldSpecified;
            }
            set {
                this.gerResultFieldSpecified = value;
                this.RaisePropertyChanged("gerResultSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public double gerScores {
            get {
                return this.gerScoresField;
            }
            set {
                this.gerScoresField = value;
                this.RaisePropertyChanged("gerScores");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool gerScoresSpecified {
            get {
                return this.gerScoresFieldSpecified;
            }
            set {
                this.gerScoresFieldSpecified = value;
                this.RaisePropertyChanged("gerScoresSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public System.DateTime gerTime {
            get {
                return this.gerTimeField;
            }
            set {
                this.gerTimeField = value;
                this.RaisePropertyChanged("gerTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool gerTimeSpecified {
            get {
                return this.gerTimeFieldSpecified;
            }
            set {
                this.gerTimeFieldSpecified = value;
                this.RaisePropertyChanged("gerTimeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public long gewtId {
            get {
                return this.gewtIdField;
            }
            set {
                this.gewtIdField = value;
                this.RaisePropertyChanged("gewtId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool gewtIdSpecified {
            get {
                return this.gewtIdFieldSpecified;
            }
            set {
                this.gewtIdFieldSpecified = value;
                this.RaisePropertyChanged("gewtIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string gsId {
            get {
                return this.gsIdField;
            }
            set {
                this.gsIdField = value;
                this.RaisePropertyChanged("gsId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string gsewiId {
            get {
                return this.gsewiIdField;
            }
            set {
                this.gsewiIdField = value;
                this.RaisePropertyChanged("gsewiId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string gsewiName {
            get {
                return this.gsewiNameField;
            }
            set {
                this.gsewiNameField = value;
                this.RaisePropertyChanged("gsewiName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string gtpId {
            get {
                return this.gtpIdField;
            }
            set {
                this.gtpIdField = value;
                this.RaisePropertyChanged("gtpId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string optCoId {
            get {
                return this.optCoIdField;
            }
            set {
                this.optCoIdField = value;
                this.RaisePropertyChanged("optCoId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string optId {
            get {
                return this.optIdField;
            }
            set {
                this.optIdField = value;
                this.RaisePropertyChanged("optId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public System.DateTime optTime {
            get {
                return this.optTimeField;
            }
            set {
                this.optTimeField = value;
                this.RaisePropertyChanged("optTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool optTimeSpecified {
            get {
                return this.optTimeFieldSpecified;
            }
            set {
                this.optTimeFieldSpecified = value;
                this.RaisePropertyChanged("optTimeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
                this.RaisePropertyChanged("remark");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public int state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
                this.RaisePropertyChanged("state");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool stateSpecified {
            get {
                return this.stateFieldSpecified;
            }
            set {
                this.stateFieldSpecified = value;
                this.RaisePropertyChanged("stateSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(gpEvalResultWebDO))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.govpurchase.opensource.com/")]
    public abstract partial class baseEntity : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.govpurchase.opensource.com/")]
    public partial class saveResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private resultDO returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public resultDO @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.govpurchase.opensource.com/")]
    public partial class resultDO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codeField;
        
        private byte[] fileContentField;
        
        private string messageField;
        
        private object objField;
        
        private object[] objListField;
        
        private bool successField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=1)]
        public byte[] fileContent {
            get {
                return this.fileContentField;
            }
            set {
                this.fileContentField = value;
                this.RaisePropertyChanged("fileContent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public object obj {
            get {
                return this.objField;
            }
            set {
                this.objField = value;
                this.RaisePropertyChanged("obj");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("objList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public object[] objList {
            get {
                return this.objListField;
            }
            set {
                this.objListField = value;
                this.RaisePropertyChanged("objList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public bool success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
                this.RaisePropertyChanged("success");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.govpurchase.opensource.com/")]
    public partial class save : object, System.ComponentModel.INotifyPropertyChanged {
        
        private gpEvalResultWebDO gpEvalResultWebDOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public gpEvalResultWebDO GpEvalResultWebDO {
            get {
                return this.gpEvalResultWebDOField;
            }
            set {
                this.gpEvalResultWebDOField = value;
                this.RaisePropertyChanged("GpEvalResultWebDO");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="save", WrapperNamespace="http://webservice.govpurchase.opensource.com/", IsWrapped=true)]
    public partial class save1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.govpurchase.opensource.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Summer.CompetitiveTender.Service.ServiceReferenceGpEvalResult.gpEvalResultWebDO GpEvalResultWebDO;
        
        public save1() {
        }
        
        public save1(Summer.CompetitiveTender.Service.ServiceReferenceGpEvalResult.gpEvalResultWebDO GpEvalResultWebDO) {
            this.GpEvalResultWebDO = GpEvalResultWebDO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="saveResponse", WrapperNamespace="http://webservice.govpurchase.opensource.com/", IsWrapped=true)]
    public partial class saveResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.govpurchase.opensource.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Summer.CompetitiveTender.Service.ServiceReferenceGpEvalResult.resultDO @return;
        
        public saveResponse1() {
        }
        
        public saveResponse1(Summer.CompetitiveTender.Service.ServiceReferenceGpEvalResult.resultDO @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GpEvalResultWebServiceChannel : Summer.CompetitiveTender.Service.ServiceReferenceGpEvalResult.GpEvalResultWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GpEvalResultWebServiceClient : System.ServiceModel.ClientBase<Summer.CompetitiveTender.Service.ServiceReferenceGpEvalResult.GpEvalResultWebService>, Summer.CompetitiveTender.Service.ServiceReferenceGpEvalResult.GpEvalResultWebService {
        
        public GpEvalResultWebServiceClient() {
        }
        
        public GpEvalResultWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GpEvalResultWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GpEvalResultWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GpEvalResultWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Summer.CompetitiveTender.Service.ServiceReferenceGpEvalResult.saveResponse1 Summer.CompetitiveTender.Service.ServiceReferenceGpEvalResult.GpEvalResultWebService.save(Summer.CompetitiveTender.Service.ServiceReferenceGpEvalResult.save1 request) {
            return base.Channel.save(request);
        }
        
        public Summer.CompetitiveTender.Service.ServiceReferenceGpEvalResult.resultDO save(Summer.CompetitiveTender.Service.ServiceReferenceGpEvalResult.gpEvalResultWebDO GpEvalResultWebDO) {
            Summer.CompetitiveTender.Service.ServiceReferenceGpEvalResult.save1 inValue = new Summer.CompetitiveTender.Service.ServiceReferenceGpEvalResult.save1();
            inValue.GpEvalResultWebDO = GpEvalResultWebDO;
            Summer.CompetitiveTender.Service.ServiceReferenceGpEvalResult.saveResponse1 retVal = ((Summer.CompetitiveTender.Service.ServiceReferenceGpEvalResult.GpEvalResultWebService)(this)).save(inValue);
            return retVal.@return;
        }
    }
}
