//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Summer.CompetitiveTender.Service.ServiceReferenceGpApplyDetail {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservice.govpurchase.opensource.com/", ConfigurationName="ServiceReferenceGpApplyDetail.GpApplyDetailWebService")]
    public interface GpApplyDetailWebService {
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getApplyByIdResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getApplyById))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(applyFileDecryptResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(applyFileDecrypt))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findApplyListResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findApplyList))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getApplyFileListResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getApplyFileList))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findBidderListResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findBidderList))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(applyFileSingResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(applyFileSing))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseEntity))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Summer.CompetitiveTender.Service.ServiceReferenceGpApplyDetail.applyFileSingResponse1 applyFileSing(Summer.CompetitiveTender.Service.ServiceReferenceGpApplyDetail.applyFileSing1 request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getApplyByIdResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getApplyById))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(applyFileDecryptResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(applyFileDecrypt))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findApplyListResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findApplyList))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getApplyFileListResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getApplyFileList))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findBidderListResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findBidderList))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(applyFileSingResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(applyFileSing))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseEntity))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Summer.CompetitiveTender.Service.ServiceReferenceGpApplyDetail.findBidderListResponse1 findBidderList(Summer.CompetitiveTender.Service.ServiceReferenceGpApplyDetail.findBidderList1 request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getApplyByIdResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getApplyById))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(applyFileDecryptResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(applyFileDecrypt))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findApplyListResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findApplyList))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getApplyFileListResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getApplyFileList))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findBidderListResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findBidderList))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(applyFileSingResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(applyFileSing))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseEntity))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Summer.CompetitiveTender.Service.ServiceReferenceGpApplyDetail.getApplyFileListResponse1 getApplyFileList(Summer.CompetitiveTender.Service.ServiceReferenceGpApplyDetail.getApplyFileList1 request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getApplyByIdResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getApplyById))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(applyFileDecryptResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(applyFileDecrypt))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findApplyListResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findApplyList))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getApplyFileListResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getApplyFileList))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findBidderListResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findBidderList))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(applyFileSingResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(applyFileSing))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseEntity))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Summer.CompetitiveTender.Service.ServiceReferenceGpApplyDetail.findApplyListResponse1 findApplyList(Summer.CompetitiveTender.Service.ServiceReferenceGpApplyDetail.findApplyList1 request);
        
        // CODEGEN: 参数“gadId”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getApplyByIdResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getApplyById))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(applyFileDecryptResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(applyFileDecrypt))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findApplyListResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findApplyList))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getApplyFileListResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getApplyFileList))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findBidderListResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findBidderList))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(applyFileSingResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(applyFileSing))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseEntity))]
        Summer.CompetitiveTender.Service.ServiceReferenceGpApplyDetail.applyFileDecryptResponse1 applyFileDecrypt(Summer.CompetitiveTender.Service.ServiceReferenceGpApplyDetail.applyFileDecrypt1 request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getApplyByIdResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getApplyById))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(applyFileDecryptResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(applyFileDecrypt))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findApplyListResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findApplyList))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getApplyFileListResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getApplyFileList))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findBidderListResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findBidderList))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(applyFileSingResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(applyFileSing))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseEntity))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Summer.CompetitiveTender.Service.ServiceReferenceGpApplyDetail.getApplyByIdResponse1 getApplyById(Summer.CompetitiveTender.Service.ServiceReferenceGpApplyDetail.getApplyById1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.govpurchase.opensource.com/")]
    public partial class gpApplyDetailWebDO : baseEntity {
        
        private string bcNameField;
        
        private string decryptOutFileField;
        
        private string encryptCodeField;
        
        private int encryptStateField;
        
        private bool encryptStateFieldSpecified;
        
        private string gadBidCodeField;
        
        private string gadBidCompanyIdField;
        
        private string gadBidCompanyNameField;
        
        private string gadBidPersonIdField;
        
        private string gadBidPersonNameField;
        
        private string gadBidSuffixField;
        
        private System.DateTime gadBidTimeField;
        
        private bool gadBidTimeFieldSpecified;
        
        private string gadIdField;
        
        private string gadSignCoIdField;
        
        private string gadSignIdField;
        
        private int gadSignStateField;
        
        private bool gadSignStateFieldSpecified;
        
        private System.DateTime gadSignTimeField;
        
        private bool gadSignTimeFieldSpecified;
        
        private string gaiApplyCoIdField;
        
        private string gaiApplyCodeField;
        
        private string gaiApplyIdField;
        
        private string gaiApplyNameField;
        
        private System.DateTime gaiApplyTimeField;
        
        private bool gaiApplyTimeFieldSpecified;
        
        private string gaiIdField;
        
        private string gsIdField;
        
        private string gsNameField;
        
        private string gtfNewNameField;
        
        private string gtfOldNameField;
        
        private long gtfSizeField;
        
        private bool gtfSizeFieldSpecified;
        
        private string gtfSuffixField;
        
        private System.DateTime gtfUploadTimeField;
        
        private bool gtfUploadTimeFieldSpecified;
        
        private string gtfUrlField;
        
        private string gtpCodeField;
        
        private string gtpIdField;
        
        private string gtpNameField;
        
        private string optCompanyIdField;
        
        private string optIdField;
        
        private System.DateTime optTimeField;
        
        private bool optTimeFieldSpecified;
        
        private int registStateField;
        
        private bool registStateFieldSpecified;
        
        private System.DateTime registTimeField;
        
        private bool registTimeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string bcName {
            get {
                return this.bcNameField;
            }
            set {
                this.bcNameField = value;
                this.RaisePropertyChanged("bcName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string decryptOutFile {
            get {
                return this.decryptOutFileField;
            }
            set {
                this.decryptOutFileField = value;
                this.RaisePropertyChanged("decryptOutFile");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string encryptCode {
            get {
                return this.encryptCodeField;
            }
            set {
                this.encryptCodeField = value;
                this.RaisePropertyChanged("encryptCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int encryptState {
            get {
                return this.encryptStateField;
            }
            set {
                this.encryptStateField = value;
                this.RaisePropertyChanged("encryptState");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool encryptStateSpecified {
            get {
                return this.encryptStateFieldSpecified;
            }
            set {
                this.encryptStateFieldSpecified = value;
                this.RaisePropertyChanged("encryptStateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string gadBidCode {
            get {
                return this.gadBidCodeField;
            }
            set {
                this.gadBidCodeField = value;
                this.RaisePropertyChanged("gadBidCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string gadBidCompanyId {
            get {
                return this.gadBidCompanyIdField;
            }
            set {
                this.gadBidCompanyIdField = value;
                this.RaisePropertyChanged("gadBidCompanyId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string gadBidCompanyName {
            get {
                return this.gadBidCompanyNameField;
            }
            set {
                this.gadBidCompanyNameField = value;
                this.RaisePropertyChanged("gadBidCompanyName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string gadBidPersonId {
            get {
                return this.gadBidPersonIdField;
            }
            set {
                this.gadBidPersonIdField = value;
                this.RaisePropertyChanged("gadBidPersonId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string gadBidPersonName {
            get {
                return this.gadBidPersonNameField;
            }
            set {
                this.gadBidPersonNameField = value;
                this.RaisePropertyChanged("gadBidPersonName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string gadBidSuffix {
            get {
                return this.gadBidSuffixField;
            }
            set {
                this.gadBidSuffixField = value;
                this.RaisePropertyChanged("gadBidSuffix");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public System.DateTime gadBidTime {
            get {
                return this.gadBidTimeField;
            }
            set {
                this.gadBidTimeField = value;
                this.RaisePropertyChanged("gadBidTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool gadBidTimeSpecified {
            get {
                return this.gadBidTimeFieldSpecified;
            }
            set {
                this.gadBidTimeFieldSpecified = value;
                this.RaisePropertyChanged("gadBidTimeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string gadId {
            get {
                return this.gadIdField;
            }
            set {
                this.gadIdField = value;
                this.RaisePropertyChanged("gadId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string gadSignCoId {
            get {
                return this.gadSignCoIdField;
            }
            set {
                this.gadSignCoIdField = value;
                this.RaisePropertyChanged("gadSignCoId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string gadSignId {
            get {
                return this.gadSignIdField;
            }
            set {
                this.gadSignIdField = value;
                this.RaisePropertyChanged("gadSignId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public int gadSignState {
            get {
                return this.gadSignStateField;
            }
            set {
                this.gadSignStateField = value;
                this.RaisePropertyChanged("gadSignState");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool gadSignStateSpecified {
            get {
                return this.gadSignStateFieldSpecified;
            }
            set {
                this.gadSignStateFieldSpecified = value;
                this.RaisePropertyChanged("gadSignStateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public System.DateTime gadSignTime {
            get {
                return this.gadSignTimeField;
            }
            set {
                this.gadSignTimeField = value;
                this.RaisePropertyChanged("gadSignTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool gadSignTimeSpecified {
            get {
                return this.gadSignTimeFieldSpecified;
            }
            set {
                this.gadSignTimeFieldSpecified = value;
                this.RaisePropertyChanged("gadSignTimeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string gaiApplyCoId {
            get {
                return this.gaiApplyCoIdField;
            }
            set {
                this.gaiApplyCoIdField = value;
                this.RaisePropertyChanged("gaiApplyCoId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string gaiApplyCode {
            get {
                return this.gaiApplyCodeField;
            }
            set {
                this.gaiApplyCodeField = value;
                this.RaisePropertyChanged("gaiApplyCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string gaiApplyId {
            get {
                return this.gaiApplyIdField;
            }
            set {
                this.gaiApplyIdField = value;
                this.RaisePropertyChanged("gaiApplyId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string gaiApplyName {
            get {
                return this.gaiApplyNameField;
            }
            set {
                this.gaiApplyNameField = value;
                this.RaisePropertyChanged("gaiApplyName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public System.DateTime gaiApplyTime {
            get {
                return this.gaiApplyTimeField;
            }
            set {
                this.gaiApplyTimeField = value;
                this.RaisePropertyChanged("gaiApplyTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool gaiApplyTimeSpecified {
            get {
                return this.gaiApplyTimeFieldSpecified;
            }
            set {
                this.gaiApplyTimeFieldSpecified = value;
                this.RaisePropertyChanged("gaiApplyTimeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string gaiId {
            get {
                return this.gaiIdField;
            }
            set {
                this.gaiIdField = value;
                this.RaisePropertyChanged("gaiId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string gsId {
            get {
                return this.gsIdField;
            }
            set {
                this.gsIdField = value;
                this.RaisePropertyChanged("gsId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string gsName {
            get {
                return this.gsNameField;
            }
            set {
                this.gsNameField = value;
                this.RaisePropertyChanged("gsName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public string gtfNewName {
            get {
                return this.gtfNewNameField;
            }
            set {
                this.gtfNewNameField = value;
                this.RaisePropertyChanged("gtfNewName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public string gtfOldName {
            get {
                return this.gtfOldNameField;
            }
            set {
                this.gtfOldNameField = value;
                this.RaisePropertyChanged("gtfOldName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public long gtfSize {
            get {
                return this.gtfSizeField;
            }
            set {
                this.gtfSizeField = value;
                this.RaisePropertyChanged("gtfSize");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool gtfSizeSpecified {
            get {
                return this.gtfSizeFieldSpecified;
            }
            set {
                this.gtfSizeFieldSpecified = value;
                this.RaisePropertyChanged("gtfSizeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=27)]
        public string gtfSuffix {
            get {
                return this.gtfSuffixField;
            }
            set {
                this.gtfSuffixField = value;
                this.RaisePropertyChanged("gtfSuffix");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=28)]
        public System.DateTime gtfUploadTime {
            get {
                return this.gtfUploadTimeField;
            }
            set {
                this.gtfUploadTimeField = value;
                this.RaisePropertyChanged("gtfUploadTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool gtfUploadTimeSpecified {
            get {
                return this.gtfUploadTimeFieldSpecified;
            }
            set {
                this.gtfUploadTimeFieldSpecified = value;
                this.RaisePropertyChanged("gtfUploadTimeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=29)]
        public string gtfUrl {
            get {
                return this.gtfUrlField;
            }
            set {
                this.gtfUrlField = value;
                this.RaisePropertyChanged("gtfUrl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=30)]
        public string gtpCode {
            get {
                return this.gtpCodeField;
            }
            set {
                this.gtpCodeField = value;
                this.RaisePropertyChanged("gtpCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=31)]
        public string gtpId {
            get {
                return this.gtpIdField;
            }
            set {
                this.gtpIdField = value;
                this.RaisePropertyChanged("gtpId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=32)]
        public string gtpName {
            get {
                return this.gtpNameField;
            }
            set {
                this.gtpNameField = value;
                this.RaisePropertyChanged("gtpName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=33)]
        public string optCompanyId {
            get {
                return this.optCompanyIdField;
            }
            set {
                this.optCompanyIdField = value;
                this.RaisePropertyChanged("optCompanyId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=34)]
        public string optId {
            get {
                return this.optIdField;
            }
            set {
                this.optIdField = value;
                this.RaisePropertyChanged("optId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=35)]
        public System.DateTime optTime {
            get {
                return this.optTimeField;
            }
            set {
                this.optTimeField = value;
                this.RaisePropertyChanged("optTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool optTimeSpecified {
            get {
                return this.optTimeFieldSpecified;
            }
            set {
                this.optTimeFieldSpecified = value;
                this.RaisePropertyChanged("optTimeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=36)]
        public int registState {
            get {
                return this.registStateField;
            }
            set {
                this.registStateField = value;
                this.RaisePropertyChanged("registState");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool registStateSpecified {
            get {
                return this.registStateFieldSpecified;
            }
            set {
                this.registStateFieldSpecified = value;
                this.RaisePropertyChanged("registStateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=37)]
        public System.DateTime registTime {
            get {
                return this.registTimeField;
            }
            set {
                this.registTimeField = value;
                this.RaisePropertyChanged("registTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool registTimeSpecified {
            get {
                return this.registTimeFieldSpecified;
            }
            set {
                this.registTimeFieldSpecified = value;
                this.RaisePropertyChanged("registTimeSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(gpApplyDetailWebDO))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.govpurchase.opensource.com/")]
    public abstract partial class baseEntity : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.govpurchase.opensource.com/")]
    public partial class getApplyByIdResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private resultDO returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public resultDO @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.govpurchase.opensource.com/")]
    public partial class resultDO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codeField;
        
        private byte[] fileContentField;
        
        private string messageField;
        
        private object objField;
        
        private object[] objListField;
        
        private bool successField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=1)]
        public byte[] fileContent {
            get {
                return this.fileContentField;
            }
            set {
                this.fileContentField = value;
                this.RaisePropertyChanged("fileContent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public object obj {
            get {
                return this.objField;
            }
            set {
                this.objField = value;
                this.RaisePropertyChanged("obj");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("objList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public object[] objList {
            get {
                return this.objListField;
            }
            set {
                this.objListField = value;
                this.RaisePropertyChanged("objList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public bool success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
                this.RaisePropertyChanged("success");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.govpurchase.opensource.com/")]
    public partial class getApplyById : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string gaiApplyIdField;
        
        private string gaiApplyCoIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string gaiApplyId {
            get {
                return this.gaiApplyIdField;
            }
            set {
                this.gaiApplyIdField = value;
                this.RaisePropertyChanged("gaiApplyId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string gaiApplyCoId {
            get {
                return this.gaiApplyCoIdField;
            }
            set {
                this.gaiApplyCoIdField = value;
                this.RaisePropertyChanged("gaiApplyCoId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.govpurchase.opensource.com/")]
    public partial class applyFileDecryptResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.govpurchase.opensource.com/")]
    public partial class applyFileDecrypt : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string gadIdField;
        
        private string decryptionCipherField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string gadId {
            get {
                return this.gadIdField;
            }
            set {
                this.gadIdField = value;
                this.RaisePropertyChanged("gadId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string decryptionCipher {
            get {
                return this.decryptionCipherField;
            }
            set {
                this.decryptionCipherField = value;
                this.RaisePropertyChanged("decryptionCipher");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.govpurchase.opensource.com/")]
    public partial class findApplyListResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private resultDO returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public resultDO @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.govpurchase.opensource.com/")]
    public partial class findApplyList : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string gtpIdField;
        
        private string gsIdField;
        
        private string gtpNameField;
        
        private string gtpCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string gtpId {
            get {
                return this.gtpIdField;
            }
            set {
                this.gtpIdField = value;
                this.RaisePropertyChanged("gtpId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string gsId {
            get {
                return this.gsIdField;
            }
            set {
                this.gsIdField = value;
                this.RaisePropertyChanged("gsId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string gtpName {
            get {
                return this.gtpNameField;
            }
            set {
                this.gtpNameField = value;
                this.RaisePropertyChanged("gtpName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string gtpCode {
            get {
                return this.gtpCodeField;
            }
            set {
                this.gtpCodeField = value;
                this.RaisePropertyChanged("gtpCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.govpurchase.opensource.com/")]
    public partial class getApplyFileListResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private resultDO returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public resultDO @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.govpurchase.opensource.com/")]
    public partial class getApplyFileList : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string gsIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string gsId {
            get {
                return this.gsIdField;
            }
            set {
                this.gsIdField = value;
                this.RaisePropertyChanged("gsId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.govpurchase.opensource.com/")]
    public partial class findBidderListResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private resultDO returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public resultDO @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.govpurchase.opensource.com/")]
    public partial class findBidderList : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string gtpIdField;
        
        private string gsIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string gtpId {
            get {
                return this.gtpIdField;
            }
            set {
                this.gtpIdField = value;
                this.RaisePropertyChanged("gtpId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string gsId {
            get {
                return this.gsIdField;
            }
            set {
                this.gsIdField = value;
                this.RaisePropertyChanged("gsId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.govpurchase.opensource.com/")]
    public partial class applyFileSingResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private resultDO returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public resultDO @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.govpurchase.opensource.com/")]
    public partial class applyFileSing : object, System.ComponentModel.INotifyPropertyChanged {
        
        private gpApplyDetailWebDO gpApplyDetailWebDOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public gpApplyDetailWebDO GpApplyDetailWebDO {
            get {
                return this.gpApplyDetailWebDOField;
            }
            set {
                this.gpApplyDetailWebDOField = value;
                this.RaisePropertyChanged("GpApplyDetailWebDO");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="applyFileSing", WrapperNamespace="http://webservice.govpurchase.opensource.com/", IsWrapped=true)]
    public partial class applyFileSing1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.govpurchase.opensource.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Summer.CompetitiveTender.Service.ServiceReferenceGpApplyDetail.gpApplyDetailWebDO GpApplyDetailWebDO;
        
        public applyFileSing1() {
        }
        
        public applyFileSing1(Summer.CompetitiveTender.Service.ServiceReferenceGpApplyDetail.gpApplyDetailWebDO GpApplyDetailWebDO) {
            this.GpApplyDetailWebDO = GpApplyDetailWebDO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="applyFileSingResponse", WrapperNamespace="http://webservice.govpurchase.opensource.com/", IsWrapped=true)]
    public partial class applyFileSingResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.govpurchase.opensource.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Summer.CompetitiveTender.Service.ServiceReferenceGpApplyDetail.resultDO @return;
        
        public applyFileSingResponse1() {
        }
        
        public applyFileSingResponse1(Summer.CompetitiveTender.Service.ServiceReferenceGpApplyDetail.resultDO @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findBidderList", WrapperNamespace="http://webservice.govpurchase.opensource.com/", IsWrapped=true)]
    public partial class findBidderList1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.govpurchase.opensource.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string gtpId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.govpurchase.opensource.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string gsId;
        
        public findBidderList1() {
        }
        
        public findBidderList1(string gtpId, string gsId) {
            this.gtpId = gtpId;
            this.gsId = gsId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findBidderListResponse", WrapperNamespace="http://webservice.govpurchase.opensource.com/", IsWrapped=true)]
    public partial class findBidderListResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.govpurchase.opensource.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Summer.CompetitiveTender.Service.ServiceReferenceGpApplyDetail.resultDO @return;
        
        public findBidderListResponse1() {
        }
        
        public findBidderListResponse1(Summer.CompetitiveTender.Service.ServiceReferenceGpApplyDetail.resultDO @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getApplyFileList", WrapperNamespace="http://webservice.govpurchase.opensource.com/", IsWrapped=true)]
    public partial class getApplyFileList1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.govpurchase.opensource.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string gsId;
        
        public getApplyFileList1() {
        }
        
        public getApplyFileList1(string gsId) {
            this.gsId = gsId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getApplyFileListResponse", WrapperNamespace="http://webservice.govpurchase.opensource.com/", IsWrapped=true)]
    public partial class getApplyFileListResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.govpurchase.opensource.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Summer.CompetitiveTender.Service.ServiceReferenceGpApplyDetail.resultDO @return;
        
        public getApplyFileListResponse1() {
        }
        
        public getApplyFileListResponse1(Summer.CompetitiveTender.Service.ServiceReferenceGpApplyDetail.resultDO @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findApplyList", WrapperNamespace="http://webservice.govpurchase.opensource.com/", IsWrapped=true)]
    public partial class findApplyList1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.govpurchase.opensource.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string gtpId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.govpurchase.opensource.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string gsId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.govpurchase.opensource.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string gtpName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.govpurchase.opensource.com/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string gtpCode;
        
        public findApplyList1() {
        }
        
        public findApplyList1(string gtpId, string gsId, string gtpName, string gtpCode) {
            this.gtpId = gtpId;
            this.gsId = gsId;
            this.gtpName = gtpName;
            this.gtpCode = gtpCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findApplyListResponse", WrapperNamespace="http://webservice.govpurchase.opensource.com/", IsWrapped=true)]
    public partial class findApplyListResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.govpurchase.opensource.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Summer.CompetitiveTender.Service.ServiceReferenceGpApplyDetail.resultDO @return;
        
        public findApplyListResponse1() {
        }
        
        public findApplyListResponse1(Summer.CompetitiveTender.Service.ServiceReferenceGpApplyDetail.resultDO @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="applyFileDecrypt", WrapperNamespace="http://webservice.govpurchase.opensource.com/", IsWrapped=true)]
    public partial class applyFileDecrypt1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.govpurchase.opensource.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string gadId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.govpurchase.opensource.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string decryptionCipher;
        
        public applyFileDecrypt1() {
        }
        
        public applyFileDecrypt1(string gadId, string decryptionCipher) {
            this.gadId = gadId;
            this.decryptionCipher = decryptionCipher;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="applyFileDecryptResponse", WrapperNamespace="http://webservice.govpurchase.opensource.com/", IsWrapped=true)]
    public partial class applyFileDecryptResponse1 {
        
        public applyFileDecryptResponse1() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getApplyById", WrapperNamespace="http://webservice.govpurchase.opensource.com/", IsWrapped=true)]
    public partial class getApplyById1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.govpurchase.opensource.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string gaiApplyId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.govpurchase.opensource.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string gaiApplyCoId;
        
        public getApplyById1() {
        }
        
        public getApplyById1(string gaiApplyId, string gaiApplyCoId) {
            this.gaiApplyId = gaiApplyId;
            this.gaiApplyCoId = gaiApplyCoId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getApplyByIdResponse", WrapperNamespace="http://webservice.govpurchase.opensource.com/", IsWrapped=true)]
    public partial class getApplyByIdResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.govpurchase.opensource.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Summer.CompetitiveTender.Service.ServiceReferenceGpApplyDetail.resultDO @return;
        
        public getApplyByIdResponse1() {
        }
        
        public getApplyByIdResponse1(Summer.CompetitiveTender.Service.ServiceReferenceGpApplyDetail.resultDO @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GpApplyDetailWebServiceChannel : Summer.CompetitiveTender.Service.ServiceReferenceGpApplyDetail.GpApplyDetailWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GpApplyDetailWebServiceClient : System.ServiceModel.ClientBase<Summer.CompetitiveTender.Service.ServiceReferenceGpApplyDetail.GpApplyDetailWebService>, Summer.CompetitiveTender.Service.ServiceReferenceGpApplyDetail.GpApplyDetailWebService {
        
        public GpApplyDetailWebServiceClient() {
        }
        
        public GpApplyDetailWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GpApplyDetailWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GpApplyDetailWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GpApplyDetailWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Summer.CompetitiveTender.Service.ServiceReferenceGpApplyDetail.applyFileSingResponse1 Summer.CompetitiveTender.Service.ServiceReferenceGpApplyDetail.GpApplyDetailWebService.applyFileSing(Summer.CompetitiveTender.Service.ServiceReferenceGpApplyDetail.applyFileSing1 request) {
            return base.Channel.applyFileSing(request);
        }
        
        public Summer.CompetitiveTender.Service.ServiceReferenceGpApplyDetail.resultDO applyFileSing(Summer.CompetitiveTender.Service.ServiceReferenceGpApplyDetail.gpApplyDetailWebDO GpApplyDetailWebDO) {
            Summer.CompetitiveTender.Service.ServiceReferenceGpApplyDetail.applyFileSing1 inValue = new Summer.CompetitiveTender.Service.ServiceReferenceGpApplyDetail.applyFileSing1();
            inValue.GpApplyDetailWebDO = GpApplyDetailWebDO;
            Summer.CompetitiveTender.Service.ServiceReferenceGpApplyDetail.applyFileSingResponse1 retVal = ((Summer.CompetitiveTender.Service.ServiceReferenceGpApplyDetail.GpApplyDetailWebService)(this)).applyFileSing(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Summer.CompetitiveTender.Service.ServiceReferenceGpApplyDetail.findBidderListResponse1 Summer.CompetitiveTender.Service.ServiceReferenceGpApplyDetail.GpApplyDetailWebService.findBidderList(Summer.CompetitiveTender.Service.ServiceReferenceGpApplyDetail.findBidderList1 request) {
            return base.Channel.findBidderList(request);
        }
        
        public Summer.CompetitiveTender.Service.ServiceReferenceGpApplyDetail.resultDO findBidderList(string gtpId, string gsId) {
            Summer.CompetitiveTender.Service.ServiceReferenceGpApplyDetail.findBidderList1 inValue = new Summer.CompetitiveTender.Service.ServiceReferenceGpApplyDetail.findBidderList1();
            inValue.gtpId = gtpId;
            inValue.gsId = gsId;
            Summer.CompetitiveTender.Service.ServiceReferenceGpApplyDetail.findBidderListResponse1 retVal = ((Summer.CompetitiveTender.Service.ServiceReferenceGpApplyDetail.GpApplyDetailWebService)(this)).findBidderList(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Summer.CompetitiveTender.Service.ServiceReferenceGpApplyDetail.getApplyFileListResponse1 Summer.CompetitiveTender.Service.ServiceReferenceGpApplyDetail.GpApplyDetailWebService.getApplyFileList(Summer.CompetitiveTender.Service.ServiceReferenceGpApplyDetail.getApplyFileList1 request) {
            return base.Channel.getApplyFileList(request);
        }
        
        public Summer.CompetitiveTender.Service.ServiceReferenceGpApplyDetail.resultDO getApplyFileList(string gsId) {
            Summer.CompetitiveTender.Service.ServiceReferenceGpApplyDetail.getApplyFileList1 inValue = new Summer.CompetitiveTender.Service.ServiceReferenceGpApplyDetail.getApplyFileList1();
            inValue.gsId = gsId;
            Summer.CompetitiveTender.Service.ServiceReferenceGpApplyDetail.getApplyFileListResponse1 retVal = ((Summer.CompetitiveTender.Service.ServiceReferenceGpApplyDetail.GpApplyDetailWebService)(this)).getApplyFileList(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Summer.CompetitiveTender.Service.ServiceReferenceGpApplyDetail.findApplyListResponse1 Summer.CompetitiveTender.Service.ServiceReferenceGpApplyDetail.GpApplyDetailWebService.findApplyList(Summer.CompetitiveTender.Service.ServiceReferenceGpApplyDetail.findApplyList1 request) {
            return base.Channel.findApplyList(request);
        }
        
        public Summer.CompetitiveTender.Service.ServiceReferenceGpApplyDetail.resultDO findApplyList(string gtpId, string gsId, string gtpName, string gtpCode) {
            Summer.CompetitiveTender.Service.ServiceReferenceGpApplyDetail.findApplyList1 inValue = new Summer.CompetitiveTender.Service.ServiceReferenceGpApplyDetail.findApplyList1();
            inValue.gtpId = gtpId;
            inValue.gsId = gsId;
            inValue.gtpName = gtpName;
            inValue.gtpCode = gtpCode;
            Summer.CompetitiveTender.Service.ServiceReferenceGpApplyDetail.findApplyListResponse1 retVal = ((Summer.CompetitiveTender.Service.ServiceReferenceGpApplyDetail.GpApplyDetailWebService)(this)).findApplyList(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Summer.CompetitiveTender.Service.ServiceReferenceGpApplyDetail.applyFileDecryptResponse1 Summer.CompetitiveTender.Service.ServiceReferenceGpApplyDetail.GpApplyDetailWebService.applyFileDecrypt(Summer.CompetitiveTender.Service.ServiceReferenceGpApplyDetail.applyFileDecrypt1 request) {
            return base.Channel.applyFileDecrypt(request);
        }
        
        public void applyFileDecrypt(string gadId, string decryptionCipher) {
            Summer.CompetitiveTender.Service.ServiceReferenceGpApplyDetail.applyFileDecrypt1 inValue = new Summer.CompetitiveTender.Service.ServiceReferenceGpApplyDetail.applyFileDecrypt1();
            inValue.gadId = gadId;
            inValue.decryptionCipher = decryptionCipher;
            Summer.CompetitiveTender.Service.ServiceReferenceGpApplyDetail.applyFileDecryptResponse1 retVal = ((Summer.CompetitiveTender.Service.ServiceReferenceGpApplyDetail.GpApplyDetailWebService)(this)).applyFileDecrypt(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Summer.CompetitiveTender.Service.ServiceReferenceGpApplyDetail.getApplyByIdResponse1 Summer.CompetitiveTender.Service.ServiceReferenceGpApplyDetail.GpApplyDetailWebService.getApplyById(Summer.CompetitiveTender.Service.ServiceReferenceGpApplyDetail.getApplyById1 request) {
            return base.Channel.getApplyById(request);
        }
        
        public Summer.CompetitiveTender.Service.ServiceReferenceGpApplyDetail.resultDO getApplyById(string gaiApplyId, string gaiApplyCoId) {
            Summer.CompetitiveTender.Service.ServiceReferenceGpApplyDetail.getApplyById1 inValue = new Summer.CompetitiveTender.Service.ServiceReferenceGpApplyDetail.getApplyById1();
            inValue.gaiApplyId = gaiApplyId;
            inValue.gaiApplyCoId = gaiApplyCoId;
            Summer.CompetitiveTender.Service.ServiceReferenceGpApplyDetail.getApplyByIdResponse1 retVal = ((Summer.CompetitiveTender.Service.ServiceReferenceGpApplyDetail.GpApplyDetailWebService)(this)).getApplyById(inValue);
            return retVal.@return;
        }
    }
}
