//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Summer.CompetitiveTender.Service.ServiceReferenceGpBidQuestions {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservice.govpurchase.opensource.com/", ConfigurationName="ServiceReferenceGpBidQuestions.GpBidQuestionsWebService")]
    public interface GpBidQuestionsWebService {
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findListResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findList))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(removeResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(remove))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(editResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(edit))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(addResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(add))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseEntity))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Summer.CompetitiveTender.Service.ServiceReferenceGpBidQuestions.addResponse1 add(Summer.CompetitiveTender.Service.ServiceReferenceGpBidQuestions.add1 request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findListResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findList))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(removeResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(remove))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(editResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(edit))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(addResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(add))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseEntity))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Summer.CompetitiveTender.Service.ServiceReferenceGpBidQuestions.editResponse1 edit(Summer.CompetitiveTender.Service.ServiceReferenceGpBidQuestions.edit1 request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findListResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findList))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(removeResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(remove))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(editResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(edit))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(addResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(add))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseEntity))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Summer.CompetitiveTender.Service.ServiceReferenceGpBidQuestions.removeResponse1 remove(Summer.CompetitiveTender.Service.ServiceReferenceGpBidQuestions.remove1 request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findListResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findList))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(removeResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(remove))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(editResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(edit))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(addResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(add))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseEntity))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Summer.CompetitiveTender.Service.ServiceReferenceGpBidQuestions.findListResponse1 findList(Summer.CompetitiveTender.Service.ServiceReferenceGpBidQuestions.findList1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.govpurchase.opensource.com/")]
    public partial class gpBidQuestionsWebDO : baseEntity {
        
        private int evalStateField;
        
        private bool evalStateFieldSpecified;
        
        private string gbqAgainstCoNameField;
        
        private string gbqCodeField;
        
        private string gbqConTentField;
        
        private System.DateTime gbqEndTimeField;
        
        private bool gbqEndTimeFieldSpecified;
        
        private string gbqIdField;
        
        private System.DateTime gbqProposedTimeField;
        
        private bool gbqProposedTimeFieldSpecified;
        
        private string gbqProposerIdField;
        
        private string gbqProposerNameField;
        
        private string gsIdField;
        
        private string gtpIdField;
        
        private int isEndField;
        
        private bool isEndFieldSpecified;
        
        private int stateField;
        
        private bool stateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int evalState {
            get {
                return this.evalStateField;
            }
            set {
                this.evalStateField = value;
                this.RaisePropertyChanged("evalState");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool evalStateSpecified {
            get {
                return this.evalStateFieldSpecified;
            }
            set {
                this.evalStateFieldSpecified = value;
                this.RaisePropertyChanged("evalStateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string gbqAgainstCoName {
            get {
                return this.gbqAgainstCoNameField;
            }
            set {
                this.gbqAgainstCoNameField = value;
                this.RaisePropertyChanged("gbqAgainstCoName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string gbqCode {
            get {
                return this.gbqCodeField;
            }
            set {
                this.gbqCodeField = value;
                this.RaisePropertyChanged("gbqCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string gbqConTent {
            get {
                return this.gbqConTentField;
            }
            set {
                this.gbqConTentField = value;
                this.RaisePropertyChanged("gbqConTent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public System.DateTime gbqEndTime {
            get {
                return this.gbqEndTimeField;
            }
            set {
                this.gbqEndTimeField = value;
                this.RaisePropertyChanged("gbqEndTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool gbqEndTimeSpecified {
            get {
                return this.gbqEndTimeFieldSpecified;
            }
            set {
                this.gbqEndTimeFieldSpecified = value;
                this.RaisePropertyChanged("gbqEndTimeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string gbqId {
            get {
                return this.gbqIdField;
            }
            set {
                this.gbqIdField = value;
                this.RaisePropertyChanged("gbqId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public System.DateTime gbqProposedTime {
            get {
                return this.gbqProposedTimeField;
            }
            set {
                this.gbqProposedTimeField = value;
                this.RaisePropertyChanged("gbqProposedTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool gbqProposedTimeSpecified {
            get {
                return this.gbqProposedTimeFieldSpecified;
            }
            set {
                this.gbqProposedTimeFieldSpecified = value;
                this.RaisePropertyChanged("gbqProposedTimeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string gbqProposerId {
            get {
                return this.gbqProposerIdField;
            }
            set {
                this.gbqProposerIdField = value;
                this.RaisePropertyChanged("gbqProposerId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string gbqProposerName {
            get {
                return this.gbqProposerNameField;
            }
            set {
                this.gbqProposerNameField = value;
                this.RaisePropertyChanged("gbqProposerName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string gsId {
            get {
                return this.gsIdField;
            }
            set {
                this.gsIdField = value;
                this.RaisePropertyChanged("gsId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string gtpId {
            get {
                return this.gtpIdField;
            }
            set {
                this.gtpIdField = value;
                this.RaisePropertyChanged("gtpId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public int isEnd {
            get {
                return this.isEndField;
            }
            set {
                this.isEndField = value;
                this.RaisePropertyChanged("isEnd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isEndSpecified {
            get {
                return this.isEndFieldSpecified;
            }
            set {
                this.isEndFieldSpecified = value;
                this.RaisePropertyChanged("isEndSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public int state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
                this.RaisePropertyChanged("state");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool stateSpecified {
            get {
                return this.stateFieldSpecified;
            }
            set {
                this.stateFieldSpecified = value;
                this.RaisePropertyChanged("stateSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(gpBidQuestionsWebDO))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.govpurchase.opensource.com/")]
    public abstract partial class baseEntity : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.govpurchase.opensource.com/")]
    public partial class findListResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private resultDO returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public resultDO @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.govpurchase.opensource.com/")]
    public partial class resultDO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codeField;
        
        private byte[] fileContentField;
        
        private string messageField;
        
        private object objField;
        
        private object[] objListField;
        
        private bool successField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=1)]
        public byte[] fileContent {
            get {
                return this.fileContentField;
            }
            set {
                this.fileContentField = value;
                this.RaisePropertyChanged("fileContent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public object obj {
            get {
                return this.objField;
            }
            set {
                this.objField = value;
                this.RaisePropertyChanged("obj");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("objList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public object[] objList {
            get {
                return this.objListField;
            }
            set {
                this.objListField = value;
                this.RaisePropertyChanged("objList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public bool success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
                this.RaisePropertyChanged("success");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.govpurchase.opensource.com/")]
    public partial class findList : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string gtpIdField;
        
        private string gsIdField;
        
        private string gbqAgainstCoNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string gtpId {
            get {
                return this.gtpIdField;
            }
            set {
                this.gtpIdField = value;
                this.RaisePropertyChanged("gtpId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string gsId {
            get {
                return this.gsIdField;
            }
            set {
                this.gsIdField = value;
                this.RaisePropertyChanged("gsId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string gbqAgainstCoName {
            get {
                return this.gbqAgainstCoNameField;
            }
            set {
                this.gbqAgainstCoNameField = value;
                this.RaisePropertyChanged("gbqAgainstCoName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.govpurchase.opensource.com/")]
    public partial class removeResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private resultDO returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public resultDO @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.govpurchase.opensource.com/")]
    public partial class remove : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string gbqIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string gbqId {
            get {
                return this.gbqIdField;
            }
            set {
                this.gbqIdField = value;
                this.RaisePropertyChanged("gbqId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.govpurchase.opensource.com/")]
    public partial class editResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private resultDO returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public resultDO @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.govpurchase.opensource.com/")]
    public partial class edit : object, System.ComponentModel.INotifyPropertyChanged {
        
        private gpBidQuestionsWebDO gpBidQuestionsWebDOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public gpBidQuestionsWebDO GpBidQuestionsWebDO {
            get {
                return this.gpBidQuestionsWebDOField;
            }
            set {
                this.gpBidQuestionsWebDOField = value;
                this.RaisePropertyChanged("GpBidQuestionsWebDO");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.govpurchase.opensource.com/")]
    public partial class addResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private resultDO returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public resultDO @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.govpurchase.opensource.com/")]
    public partial class add : object, System.ComponentModel.INotifyPropertyChanged {
        
        private gpBidQuestionsWebDO gpBidQuestionsWebDOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public gpBidQuestionsWebDO GpBidQuestionsWebDO {
            get {
                return this.gpBidQuestionsWebDOField;
            }
            set {
                this.gpBidQuestionsWebDOField = value;
                this.RaisePropertyChanged("GpBidQuestionsWebDO");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="add", WrapperNamespace="http://webservice.govpurchase.opensource.com/", IsWrapped=true)]
    public partial class add1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.govpurchase.opensource.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Summer.CompetitiveTender.Service.ServiceReferenceGpBidQuestions.gpBidQuestionsWebDO GpBidQuestionsWebDO;
        
        public add1() {
        }
        
        public add1(Summer.CompetitiveTender.Service.ServiceReferenceGpBidQuestions.gpBidQuestionsWebDO GpBidQuestionsWebDO) {
            this.GpBidQuestionsWebDO = GpBidQuestionsWebDO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addResponse", WrapperNamespace="http://webservice.govpurchase.opensource.com/", IsWrapped=true)]
    public partial class addResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.govpurchase.opensource.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Summer.CompetitiveTender.Service.ServiceReferenceGpBidQuestions.resultDO @return;
        
        public addResponse1() {
        }
        
        public addResponse1(Summer.CompetitiveTender.Service.ServiceReferenceGpBidQuestions.resultDO @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="edit", WrapperNamespace="http://webservice.govpurchase.opensource.com/", IsWrapped=true)]
    public partial class edit1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.govpurchase.opensource.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Summer.CompetitiveTender.Service.ServiceReferenceGpBidQuestions.gpBidQuestionsWebDO GpBidQuestionsWebDO;
        
        public edit1() {
        }
        
        public edit1(Summer.CompetitiveTender.Service.ServiceReferenceGpBidQuestions.gpBidQuestionsWebDO GpBidQuestionsWebDO) {
            this.GpBidQuestionsWebDO = GpBidQuestionsWebDO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="editResponse", WrapperNamespace="http://webservice.govpurchase.opensource.com/", IsWrapped=true)]
    public partial class editResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.govpurchase.opensource.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Summer.CompetitiveTender.Service.ServiceReferenceGpBidQuestions.resultDO @return;
        
        public editResponse1() {
        }
        
        public editResponse1(Summer.CompetitiveTender.Service.ServiceReferenceGpBidQuestions.resultDO @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="remove", WrapperNamespace="http://webservice.govpurchase.opensource.com/", IsWrapped=true)]
    public partial class remove1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.govpurchase.opensource.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string gbqId;
        
        public remove1() {
        }
        
        public remove1(string gbqId) {
            this.gbqId = gbqId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="removeResponse", WrapperNamespace="http://webservice.govpurchase.opensource.com/", IsWrapped=true)]
    public partial class removeResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.govpurchase.opensource.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Summer.CompetitiveTender.Service.ServiceReferenceGpBidQuestions.resultDO @return;
        
        public removeResponse1() {
        }
        
        public removeResponse1(Summer.CompetitiveTender.Service.ServiceReferenceGpBidQuestions.resultDO @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findList", WrapperNamespace="http://webservice.govpurchase.opensource.com/", IsWrapped=true)]
    public partial class findList1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.govpurchase.opensource.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string gtpId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.govpurchase.opensource.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string gsId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.govpurchase.opensource.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string gbqAgainstCoName;
        
        public findList1() {
        }
        
        public findList1(string gtpId, string gsId, string gbqAgainstCoName) {
            this.gtpId = gtpId;
            this.gsId = gsId;
            this.gbqAgainstCoName = gbqAgainstCoName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findListResponse", WrapperNamespace="http://webservice.govpurchase.opensource.com/", IsWrapped=true)]
    public partial class findListResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.govpurchase.opensource.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Summer.CompetitiveTender.Service.ServiceReferenceGpBidQuestions.resultDO @return;
        
        public findListResponse1() {
        }
        
        public findListResponse1(Summer.CompetitiveTender.Service.ServiceReferenceGpBidQuestions.resultDO @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GpBidQuestionsWebServiceChannel : Summer.CompetitiveTender.Service.ServiceReferenceGpBidQuestions.GpBidQuestionsWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GpBidQuestionsWebServiceClient : System.ServiceModel.ClientBase<Summer.CompetitiveTender.Service.ServiceReferenceGpBidQuestions.GpBidQuestionsWebService>, Summer.CompetitiveTender.Service.ServiceReferenceGpBidQuestions.GpBidQuestionsWebService {
        
        public GpBidQuestionsWebServiceClient() {
        }
        
        public GpBidQuestionsWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GpBidQuestionsWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GpBidQuestionsWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GpBidQuestionsWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Summer.CompetitiveTender.Service.ServiceReferenceGpBidQuestions.addResponse1 Summer.CompetitiveTender.Service.ServiceReferenceGpBidQuestions.GpBidQuestionsWebService.add(Summer.CompetitiveTender.Service.ServiceReferenceGpBidQuestions.add1 request) {
            return base.Channel.add(request);
        }
        
        public Summer.CompetitiveTender.Service.ServiceReferenceGpBidQuestions.resultDO add(Summer.CompetitiveTender.Service.ServiceReferenceGpBidQuestions.gpBidQuestionsWebDO GpBidQuestionsWebDO) {
            Summer.CompetitiveTender.Service.ServiceReferenceGpBidQuestions.add1 inValue = new Summer.CompetitiveTender.Service.ServiceReferenceGpBidQuestions.add1();
            inValue.GpBidQuestionsWebDO = GpBidQuestionsWebDO;
            Summer.CompetitiveTender.Service.ServiceReferenceGpBidQuestions.addResponse1 retVal = ((Summer.CompetitiveTender.Service.ServiceReferenceGpBidQuestions.GpBidQuestionsWebService)(this)).add(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Summer.CompetitiveTender.Service.ServiceReferenceGpBidQuestions.editResponse1 Summer.CompetitiveTender.Service.ServiceReferenceGpBidQuestions.GpBidQuestionsWebService.edit(Summer.CompetitiveTender.Service.ServiceReferenceGpBidQuestions.edit1 request) {
            return base.Channel.edit(request);
        }
        
        public Summer.CompetitiveTender.Service.ServiceReferenceGpBidQuestions.resultDO edit(Summer.CompetitiveTender.Service.ServiceReferenceGpBidQuestions.gpBidQuestionsWebDO GpBidQuestionsWebDO) {
            Summer.CompetitiveTender.Service.ServiceReferenceGpBidQuestions.edit1 inValue = new Summer.CompetitiveTender.Service.ServiceReferenceGpBidQuestions.edit1();
            inValue.GpBidQuestionsWebDO = GpBidQuestionsWebDO;
            Summer.CompetitiveTender.Service.ServiceReferenceGpBidQuestions.editResponse1 retVal = ((Summer.CompetitiveTender.Service.ServiceReferenceGpBidQuestions.GpBidQuestionsWebService)(this)).edit(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Summer.CompetitiveTender.Service.ServiceReferenceGpBidQuestions.removeResponse1 Summer.CompetitiveTender.Service.ServiceReferenceGpBidQuestions.GpBidQuestionsWebService.remove(Summer.CompetitiveTender.Service.ServiceReferenceGpBidQuestions.remove1 request) {
            return base.Channel.remove(request);
        }
        
        public Summer.CompetitiveTender.Service.ServiceReferenceGpBidQuestions.resultDO remove(string gbqId) {
            Summer.CompetitiveTender.Service.ServiceReferenceGpBidQuestions.remove1 inValue = new Summer.CompetitiveTender.Service.ServiceReferenceGpBidQuestions.remove1();
            inValue.gbqId = gbqId;
            Summer.CompetitiveTender.Service.ServiceReferenceGpBidQuestions.removeResponse1 retVal = ((Summer.CompetitiveTender.Service.ServiceReferenceGpBidQuestions.GpBidQuestionsWebService)(this)).remove(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Summer.CompetitiveTender.Service.ServiceReferenceGpBidQuestions.findListResponse1 Summer.CompetitiveTender.Service.ServiceReferenceGpBidQuestions.GpBidQuestionsWebService.findList(Summer.CompetitiveTender.Service.ServiceReferenceGpBidQuestions.findList1 request) {
            return base.Channel.findList(request);
        }
        
        public Summer.CompetitiveTender.Service.ServiceReferenceGpBidQuestions.resultDO findList(string gtpId, string gsId, string gbqAgainstCoName) {
            Summer.CompetitiveTender.Service.ServiceReferenceGpBidQuestions.findList1 inValue = new Summer.CompetitiveTender.Service.ServiceReferenceGpBidQuestions.findList1();
            inValue.gtpId = gtpId;
            inValue.gsId = gsId;
            inValue.gbqAgainstCoName = gbqAgainstCoName;
            Summer.CompetitiveTender.Service.ServiceReferenceGpBidQuestions.findListResponse1 retVal = ((Summer.CompetitiveTender.Service.ServiceReferenceGpBidQuestions.GpBidQuestionsWebService)(this)).findList(inValue);
            return retVal.@return;
        }
    }
}
