//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Summer.CompetitiveTender.Service.ServiceReferenceGpTemplateNode {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservice.govpurchase.opensource.com/", ConfigurationName="ServiceReferenceGpTemplateNode.GpTemplateNodeWebService")]
    public interface GpTemplateNodeWebService {
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findListResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findList))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(removeResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(remove))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getByIdResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getById))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(editResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(edit))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(addResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(add))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseEntity))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Summer.CompetitiveTender.Service.ServiceReferenceGpTemplateNode.addResponse1 add(Summer.CompetitiveTender.Service.ServiceReferenceGpTemplateNode.add1 request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findListResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findList))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(removeResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(remove))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getByIdResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getById))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(editResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(edit))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(addResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(add))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseEntity))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Summer.CompetitiveTender.Service.ServiceReferenceGpTemplateNode.editResponse1 edit(Summer.CompetitiveTender.Service.ServiceReferenceGpTemplateNode.edit1 request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findListResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findList))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(removeResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(remove))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getByIdResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getById))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(editResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(edit))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(addResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(add))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseEntity))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Summer.CompetitiveTender.Service.ServiceReferenceGpTemplateNode.getByIdResponse1 getById(Summer.CompetitiveTender.Service.ServiceReferenceGpTemplateNode.getById1 request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findListResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findList))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(removeResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(remove))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getByIdResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getById))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(editResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(edit))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(addResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(add))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseEntity))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Summer.CompetitiveTender.Service.ServiceReferenceGpTemplateNode.removeResponse1 remove(Summer.CompetitiveTender.Service.ServiceReferenceGpTemplateNode.remove1 request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findListResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findList))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(removeResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(remove))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getByIdResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getById))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(editResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(edit))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(addResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(add))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseEntity))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Summer.CompetitiveTender.Service.ServiceReferenceGpTemplateNode.findListResponse1 findList(Summer.CompetitiveTender.Service.ServiceReferenceGpTemplateNode.findList1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.govpurchase.opensource.com/")]
    public partial class gpTemplateNodeWebDO : baseEntity {
        
        private string adtCoIdField;
        
        private string adtIdField;
        
        private System.DateTime adtTimeField;
        
        private bool adtTimeFieldSpecified;
        
        private int biderEditStateField;
        
        private bool biderEditStateFieldSpecified;
        
        private int bossEditStateField;
        
        private bool bossEditStateFieldSpecified;
        
        private int carryStateField;
        
        private bool carryStateFieldSpecified;
        
        private int delStateField;
        
        private bool delStateFieldSpecified;
        
        private int editStateField;
        
        private bool editStateFieldSpecified;
        
        private string gtIdField;
        
        private int gtnAttrField;
        
        private bool gtnAttrFieldSpecified;
        
        private string gtnAttrNameField;
        
        private string gtnCodeField;
        
        private int gtnDocTypeField;
        
        private bool gtnDocTypeFieldSpecified;
        
        private string gtnFileNameField;
        
        private int gtnFiletypeField;
        
        private bool gtnFiletypeFieldSpecified;
        
        private string gtnFiletypeNameField;
        
        private long gtnIdField;
        
        private bool gtnIdFieldSpecified;
        
        private string gtnNameField;
        
        private long gtnPidField;
        
        private bool gtnPidFieldSpecified;
        
        private string gtnUrlField;
        
        private string optCoIdField;
        
        private string optIdField;
        
        private System.DateTime optTimeField;
        
        private bool optTimeFieldSpecified;
        
        private int sortField;
        
        private bool sortFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string adtCoId {
            get {
                return this.adtCoIdField;
            }
            set {
                this.adtCoIdField = value;
                this.RaisePropertyChanged("adtCoId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string adtId {
            get {
                return this.adtIdField;
            }
            set {
                this.adtIdField = value;
                this.RaisePropertyChanged("adtId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime adtTime {
            get {
                return this.adtTimeField;
            }
            set {
                this.adtTimeField = value;
                this.RaisePropertyChanged("adtTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool adtTimeSpecified {
            get {
                return this.adtTimeFieldSpecified;
            }
            set {
                this.adtTimeFieldSpecified = value;
                this.RaisePropertyChanged("adtTimeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int biderEditState {
            get {
                return this.biderEditStateField;
            }
            set {
                this.biderEditStateField = value;
                this.RaisePropertyChanged("biderEditState");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool biderEditStateSpecified {
            get {
                return this.biderEditStateFieldSpecified;
            }
            set {
                this.biderEditStateFieldSpecified = value;
                this.RaisePropertyChanged("biderEditStateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int bossEditState {
            get {
                return this.bossEditStateField;
            }
            set {
                this.bossEditStateField = value;
                this.RaisePropertyChanged("bossEditState");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool bossEditStateSpecified {
            get {
                return this.bossEditStateFieldSpecified;
            }
            set {
                this.bossEditStateFieldSpecified = value;
                this.RaisePropertyChanged("bossEditStateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int carryState {
            get {
                return this.carryStateField;
            }
            set {
                this.carryStateField = value;
                this.RaisePropertyChanged("carryState");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool carryStateSpecified {
            get {
                return this.carryStateFieldSpecified;
            }
            set {
                this.carryStateFieldSpecified = value;
                this.RaisePropertyChanged("carryStateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int delState {
            get {
                return this.delStateField;
            }
            set {
                this.delStateField = value;
                this.RaisePropertyChanged("delState");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool delStateSpecified {
            get {
                return this.delStateFieldSpecified;
            }
            set {
                this.delStateFieldSpecified = value;
                this.RaisePropertyChanged("delStateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int editState {
            get {
                return this.editStateField;
            }
            set {
                this.editStateField = value;
                this.RaisePropertyChanged("editState");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool editStateSpecified {
            get {
                return this.editStateFieldSpecified;
            }
            set {
                this.editStateFieldSpecified = value;
                this.RaisePropertyChanged("editStateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string gtId {
            get {
                return this.gtIdField;
            }
            set {
                this.gtIdField = value;
                this.RaisePropertyChanged("gtId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public int gtnAttr {
            get {
                return this.gtnAttrField;
            }
            set {
                this.gtnAttrField = value;
                this.RaisePropertyChanged("gtnAttr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool gtnAttrSpecified {
            get {
                return this.gtnAttrFieldSpecified;
            }
            set {
                this.gtnAttrFieldSpecified = value;
                this.RaisePropertyChanged("gtnAttrSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string gtnAttrName {
            get {
                return this.gtnAttrNameField;
            }
            set {
                this.gtnAttrNameField = value;
                this.RaisePropertyChanged("gtnAttrName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string gtnCode {
            get {
                return this.gtnCodeField;
            }
            set {
                this.gtnCodeField = value;
                this.RaisePropertyChanged("gtnCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public int gtnDocType {
            get {
                return this.gtnDocTypeField;
            }
            set {
                this.gtnDocTypeField = value;
                this.RaisePropertyChanged("gtnDocType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool gtnDocTypeSpecified {
            get {
                return this.gtnDocTypeFieldSpecified;
            }
            set {
                this.gtnDocTypeFieldSpecified = value;
                this.RaisePropertyChanged("gtnDocTypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string gtnFileName {
            get {
                return this.gtnFileNameField;
            }
            set {
                this.gtnFileNameField = value;
                this.RaisePropertyChanged("gtnFileName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public int gtnFiletype {
            get {
                return this.gtnFiletypeField;
            }
            set {
                this.gtnFiletypeField = value;
                this.RaisePropertyChanged("gtnFiletype");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool gtnFiletypeSpecified {
            get {
                return this.gtnFiletypeFieldSpecified;
            }
            set {
                this.gtnFiletypeFieldSpecified = value;
                this.RaisePropertyChanged("gtnFiletypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string gtnFiletypeName {
            get {
                return this.gtnFiletypeNameField;
            }
            set {
                this.gtnFiletypeNameField = value;
                this.RaisePropertyChanged("gtnFiletypeName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public long gtnId {
            get {
                return this.gtnIdField;
            }
            set {
                this.gtnIdField = value;
                this.RaisePropertyChanged("gtnId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool gtnIdSpecified {
            get {
                return this.gtnIdFieldSpecified;
            }
            set {
                this.gtnIdFieldSpecified = value;
                this.RaisePropertyChanged("gtnIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string gtnName {
            get {
                return this.gtnNameField;
            }
            set {
                this.gtnNameField = value;
                this.RaisePropertyChanged("gtnName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public long gtnPid {
            get {
                return this.gtnPidField;
            }
            set {
                this.gtnPidField = value;
                this.RaisePropertyChanged("gtnPid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool gtnPidSpecified {
            get {
                return this.gtnPidFieldSpecified;
            }
            set {
                this.gtnPidFieldSpecified = value;
                this.RaisePropertyChanged("gtnPidSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string gtnUrl {
            get {
                return this.gtnUrlField;
            }
            set {
                this.gtnUrlField = value;
                this.RaisePropertyChanged("gtnUrl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string optCoId {
            get {
                return this.optCoIdField;
            }
            set {
                this.optCoIdField = value;
                this.RaisePropertyChanged("optCoId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string optId {
            get {
                return this.optIdField;
            }
            set {
                this.optIdField = value;
                this.RaisePropertyChanged("optId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public System.DateTime optTime {
            get {
                return this.optTimeField;
            }
            set {
                this.optTimeField = value;
                this.RaisePropertyChanged("optTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool optTimeSpecified {
            get {
                return this.optTimeFieldSpecified;
            }
            set {
                this.optTimeFieldSpecified = value;
                this.RaisePropertyChanged("optTimeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public int sort {
            get {
                return this.sortField;
            }
            set {
                this.sortField = value;
                this.RaisePropertyChanged("sort");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sortSpecified {
            get {
                return this.sortFieldSpecified;
            }
            set {
                this.sortFieldSpecified = value;
                this.RaisePropertyChanged("sortSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(gpTemplateNodeWebDO))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.govpurchase.opensource.com/")]
    public abstract partial class baseEntity : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.govpurchase.opensource.com/")]
    public partial class findListResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private resultDO returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public resultDO @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.govpurchase.opensource.com/")]
    public partial class resultDO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codeField;
        
        private byte[] fileContentField;
        
        private string messageField;
        
        private object objField;
        
        private object[] objListField;
        
        private bool successField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=1)]
        public byte[] fileContent {
            get {
                return this.fileContentField;
            }
            set {
                this.fileContentField = value;
                this.RaisePropertyChanged("fileContent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public object obj {
            get {
                return this.objField;
            }
            set {
                this.objField = value;
                this.RaisePropertyChanged("obj");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("objList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public object[] objList {
            get {
                return this.objListField;
            }
            set {
                this.objListField = value;
                this.RaisePropertyChanged("objList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public bool success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
                this.RaisePropertyChanged("success");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.govpurchase.opensource.com/")]
    public partial class findList : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string gtIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string gtId {
            get {
                return this.gtIdField;
            }
            set {
                this.gtIdField = value;
                this.RaisePropertyChanged("gtId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.govpurchase.opensource.com/")]
    public partial class removeResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private resultDO returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public resultDO @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.govpurchase.opensource.com/")]
    public partial class remove : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long gtnIdField;
        
        private bool gtnIdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long gtnId {
            get {
                return this.gtnIdField;
            }
            set {
                this.gtnIdField = value;
                this.RaisePropertyChanged("gtnId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool gtnIdSpecified {
            get {
                return this.gtnIdFieldSpecified;
            }
            set {
                this.gtnIdFieldSpecified = value;
                this.RaisePropertyChanged("gtnIdSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.govpurchase.opensource.com/")]
    public partial class getByIdResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private resultDO returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public resultDO @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.govpurchase.opensource.com/")]
    public partial class getById : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long gtnIdField;
        
        private bool gtnIdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long gtnId {
            get {
                return this.gtnIdField;
            }
            set {
                this.gtnIdField = value;
                this.RaisePropertyChanged("gtnId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool gtnIdSpecified {
            get {
                return this.gtnIdFieldSpecified;
            }
            set {
                this.gtnIdFieldSpecified = value;
                this.RaisePropertyChanged("gtnIdSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.govpurchase.opensource.com/")]
    public partial class editResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private resultDO returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public resultDO @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.govpurchase.opensource.com/")]
    public partial class edit : object, System.ComponentModel.INotifyPropertyChanged {
        
        private gpTemplateNodeWebDO gpTemplateNodeWebDOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public gpTemplateNodeWebDO GpTemplateNodeWebDO {
            get {
                return this.gpTemplateNodeWebDOField;
            }
            set {
                this.gpTemplateNodeWebDOField = value;
                this.RaisePropertyChanged("GpTemplateNodeWebDO");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.govpurchase.opensource.com/")]
    public partial class addResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private resultDO returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public resultDO @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.govpurchase.opensource.com/")]
    public partial class add : object, System.ComponentModel.INotifyPropertyChanged {
        
        private gpTemplateNodeWebDO gpTemplateNodeWebDOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public gpTemplateNodeWebDO GpTemplateNodeWebDO {
            get {
                return this.gpTemplateNodeWebDOField;
            }
            set {
                this.gpTemplateNodeWebDOField = value;
                this.RaisePropertyChanged("GpTemplateNodeWebDO");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="add", WrapperNamespace="http://webservice.govpurchase.opensource.com/", IsWrapped=true)]
    public partial class add1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.govpurchase.opensource.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Summer.CompetitiveTender.Service.ServiceReferenceGpTemplateNode.gpTemplateNodeWebDO GpTemplateNodeWebDO;
        
        public add1() {
        }
        
        public add1(Summer.CompetitiveTender.Service.ServiceReferenceGpTemplateNode.gpTemplateNodeWebDO GpTemplateNodeWebDO) {
            this.GpTemplateNodeWebDO = GpTemplateNodeWebDO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addResponse", WrapperNamespace="http://webservice.govpurchase.opensource.com/", IsWrapped=true)]
    public partial class addResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.govpurchase.opensource.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Summer.CompetitiveTender.Service.ServiceReferenceGpTemplateNode.resultDO @return;
        
        public addResponse1() {
        }
        
        public addResponse1(Summer.CompetitiveTender.Service.ServiceReferenceGpTemplateNode.resultDO @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="edit", WrapperNamespace="http://webservice.govpurchase.opensource.com/", IsWrapped=true)]
    public partial class edit1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.govpurchase.opensource.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Summer.CompetitiveTender.Service.ServiceReferenceGpTemplateNode.gpTemplateNodeWebDO GpTemplateNodeWebDO;
        
        public edit1() {
        }
        
        public edit1(Summer.CompetitiveTender.Service.ServiceReferenceGpTemplateNode.gpTemplateNodeWebDO GpTemplateNodeWebDO) {
            this.GpTemplateNodeWebDO = GpTemplateNodeWebDO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="editResponse", WrapperNamespace="http://webservice.govpurchase.opensource.com/", IsWrapped=true)]
    public partial class editResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.govpurchase.opensource.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Summer.CompetitiveTender.Service.ServiceReferenceGpTemplateNode.resultDO @return;
        
        public editResponse1() {
        }
        
        public editResponse1(Summer.CompetitiveTender.Service.ServiceReferenceGpTemplateNode.resultDO @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getById", WrapperNamespace="http://webservice.govpurchase.opensource.com/", IsWrapped=true)]
    public partial class getById1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.govpurchase.opensource.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long gtnId;
        
        public getById1() {
        }
        
        public getById1(long gtnId) {
            this.gtnId = gtnId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getByIdResponse", WrapperNamespace="http://webservice.govpurchase.opensource.com/", IsWrapped=true)]
    public partial class getByIdResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.govpurchase.opensource.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Summer.CompetitiveTender.Service.ServiceReferenceGpTemplateNode.resultDO @return;
        
        public getByIdResponse1() {
        }
        
        public getByIdResponse1(Summer.CompetitiveTender.Service.ServiceReferenceGpTemplateNode.resultDO @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="remove", WrapperNamespace="http://webservice.govpurchase.opensource.com/", IsWrapped=true)]
    public partial class remove1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.govpurchase.opensource.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long gtnId;
        
        public remove1() {
        }
        
        public remove1(long gtnId) {
            this.gtnId = gtnId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="removeResponse", WrapperNamespace="http://webservice.govpurchase.opensource.com/", IsWrapped=true)]
    public partial class removeResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.govpurchase.opensource.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Summer.CompetitiveTender.Service.ServiceReferenceGpTemplateNode.resultDO @return;
        
        public removeResponse1() {
        }
        
        public removeResponse1(Summer.CompetitiveTender.Service.ServiceReferenceGpTemplateNode.resultDO @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findList", WrapperNamespace="http://webservice.govpurchase.opensource.com/", IsWrapped=true)]
    public partial class findList1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.govpurchase.opensource.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string gtId;
        
        public findList1() {
        }
        
        public findList1(string gtId) {
            this.gtId = gtId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findListResponse", WrapperNamespace="http://webservice.govpurchase.opensource.com/", IsWrapped=true)]
    public partial class findListResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.govpurchase.opensource.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Summer.CompetitiveTender.Service.ServiceReferenceGpTemplateNode.resultDO @return;
        
        public findListResponse1() {
        }
        
        public findListResponse1(Summer.CompetitiveTender.Service.ServiceReferenceGpTemplateNode.resultDO @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GpTemplateNodeWebServiceChannel : Summer.CompetitiveTender.Service.ServiceReferenceGpTemplateNode.GpTemplateNodeWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GpTemplateNodeWebServiceClient : System.ServiceModel.ClientBase<Summer.CompetitiveTender.Service.ServiceReferenceGpTemplateNode.GpTemplateNodeWebService>, Summer.CompetitiveTender.Service.ServiceReferenceGpTemplateNode.GpTemplateNodeWebService {
        
        public GpTemplateNodeWebServiceClient() {
        }
        
        public GpTemplateNodeWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GpTemplateNodeWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GpTemplateNodeWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GpTemplateNodeWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Summer.CompetitiveTender.Service.ServiceReferenceGpTemplateNode.addResponse1 Summer.CompetitiveTender.Service.ServiceReferenceGpTemplateNode.GpTemplateNodeWebService.add(Summer.CompetitiveTender.Service.ServiceReferenceGpTemplateNode.add1 request) {
            return base.Channel.add(request);
        }
        
        public Summer.CompetitiveTender.Service.ServiceReferenceGpTemplateNode.resultDO add(Summer.CompetitiveTender.Service.ServiceReferenceGpTemplateNode.gpTemplateNodeWebDO GpTemplateNodeWebDO) {
            Summer.CompetitiveTender.Service.ServiceReferenceGpTemplateNode.add1 inValue = new Summer.CompetitiveTender.Service.ServiceReferenceGpTemplateNode.add1();
            inValue.GpTemplateNodeWebDO = GpTemplateNodeWebDO;
            Summer.CompetitiveTender.Service.ServiceReferenceGpTemplateNode.addResponse1 retVal = ((Summer.CompetitiveTender.Service.ServiceReferenceGpTemplateNode.GpTemplateNodeWebService)(this)).add(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Summer.CompetitiveTender.Service.ServiceReferenceGpTemplateNode.editResponse1 Summer.CompetitiveTender.Service.ServiceReferenceGpTemplateNode.GpTemplateNodeWebService.edit(Summer.CompetitiveTender.Service.ServiceReferenceGpTemplateNode.edit1 request) {
            return base.Channel.edit(request);
        }
        
        public Summer.CompetitiveTender.Service.ServiceReferenceGpTemplateNode.resultDO edit(Summer.CompetitiveTender.Service.ServiceReferenceGpTemplateNode.gpTemplateNodeWebDO GpTemplateNodeWebDO) {
            Summer.CompetitiveTender.Service.ServiceReferenceGpTemplateNode.edit1 inValue = new Summer.CompetitiveTender.Service.ServiceReferenceGpTemplateNode.edit1();
            inValue.GpTemplateNodeWebDO = GpTemplateNodeWebDO;
            Summer.CompetitiveTender.Service.ServiceReferenceGpTemplateNode.editResponse1 retVal = ((Summer.CompetitiveTender.Service.ServiceReferenceGpTemplateNode.GpTemplateNodeWebService)(this)).edit(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Summer.CompetitiveTender.Service.ServiceReferenceGpTemplateNode.getByIdResponse1 Summer.CompetitiveTender.Service.ServiceReferenceGpTemplateNode.GpTemplateNodeWebService.getById(Summer.CompetitiveTender.Service.ServiceReferenceGpTemplateNode.getById1 request) {
            return base.Channel.getById(request);
        }
        
        public Summer.CompetitiveTender.Service.ServiceReferenceGpTemplateNode.resultDO getById(long gtnId) {
            Summer.CompetitiveTender.Service.ServiceReferenceGpTemplateNode.getById1 inValue = new Summer.CompetitiveTender.Service.ServiceReferenceGpTemplateNode.getById1();
            inValue.gtnId = gtnId;
            Summer.CompetitiveTender.Service.ServiceReferenceGpTemplateNode.getByIdResponse1 retVal = ((Summer.CompetitiveTender.Service.ServiceReferenceGpTemplateNode.GpTemplateNodeWebService)(this)).getById(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Summer.CompetitiveTender.Service.ServiceReferenceGpTemplateNode.removeResponse1 Summer.CompetitiveTender.Service.ServiceReferenceGpTemplateNode.GpTemplateNodeWebService.remove(Summer.CompetitiveTender.Service.ServiceReferenceGpTemplateNode.remove1 request) {
            return base.Channel.remove(request);
        }
        
        public Summer.CompetitiveTender.Service.ServiceReferenceGpTemplateNode.resultDO remove(long gtnId) {
            Summer.CompetitiveTender.Service.ServiceReferenceGpTemplateNode.remove1 inValue = new Summer.CompetitiveTender.Service.ServiceReferenceGpTemplateNode.remove1();
            inValue.gtnId = gtnId;
            Summer.CompetitiveTender.Service.ServiceReferenceGpTemplateNode.removeResponse1 retVal = ((Summer.CompetitiveTender.Service.ServiceReferenceGpTemplateNode.GpTemplateNodeWebService)(this)).remove(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Summer.CompetitiveTender.Service.ServiceReferenceGpTemplateNode.findListResponse1 Summer.CompetitiveTender.Service.ServiceReferenceGpTemplateNode.GpTemplateNodeWebService.findList(Summer.CompetitiveTender.Service.ServiceReferenceGpTemplateNode.findList1 request) {
            return base.Channel.findList(request);
        }
        
        public Summer.CompetitiveTender.Service.ServiceReferenceGpTemplateNode.resultDO findList(string gtId) {
            Summer.CompetitiveTender.Service.ServiceReferenceGpTemplateNode.findList1 inValue = new Summer.CompetitiveTender.Service.ServiceReferenceGpTemplateNode.findList1();
            inValue.gtId = gtId;
            Summer.CompetitiveTender.Service.ServiceReferenceGpTemplateNode.findListResponse1 retVal = ((Summer.CompetitiveTender.Service.ServiceReferenceGpTemplateNode.GpTemplateNodeWebService)(this)).findList(inValue);
            return retVal.@return;
        }
    }
}
