//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Summer.CompetitiveTender.Service.ServiceReferenceGpTemplate {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.govpurchase.opensource.com/")]
    public partial class IOException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.govpurchase.opensource.com/")]
    public partial class findListResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private resultDO returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public resultDO @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.govpurchase.opensource.com/")]
    public partial class resultDO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codeField;
        
        private byte[] fileContentField;
        
        private string messageField;
        
        private object objField;
        
        private object[] objListField;
        
        private bool successField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=1)]
        public byte[] fileContent {
            get {
                return this.fileContentField;
            }
            set {
                this.fileContentField = value;
                this.RaisePropertyChanged("fileContent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public object obj {
            get {
                return this.objField;
            }
            set {
                this.objField = value;
                this.RaisePropertyChanged("obj");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("objList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public object[] objList {
            get {
                return this.objListField;
            }
            set {
                this.objListField = value;
                this.RaisePropertyChanged("objList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public bool success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
                this.RaisePropertyChanged("success");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.govpurchase.opensource.com/")]
    public partial class findList : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string auIDField;
        
        private string gtNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string auID {
            get {
                return this.auIDField;
            }
            set {
                this.auIDField = value;
                this.RaisePropertyChanged("auID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string gtName {
            get {
                return this.gtNameField;
            }
            set {
                this.gtNameField = value;
                this.RaisePropertyChanged("gtName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.govpurchase.opensource.com/")]
    public partial class getByIdResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private resultDO returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public resultDO @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.govpurchase.opensource.com/")]
    public partial class getById : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string gtIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string gtId {
            get {
                return this.gtIdField;
            }
            set {
                this.gtIdField = value;
                this.RaisePropertyChanged("gtId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.govpurchase.opensource.com/")]
    public partial class editResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private resultDO returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public resultDO @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.govpurchase.opensource.com/")]
    public partial class edit : object, System.ComponentModel.INotifyPropertyChanged {
        
        private gpTemplateWebDO gpTemplateWebDOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public gpTemplateWebDO GpTemplateWebDO {
            get {
                return this.gpTemplateWebDOField;
            }
            set {
                this.gpTemplateWebDOField = value;
                this.RaisePropertyChanged("GpTemplateWebDO");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.govpurchase.opensource.com/")]
    public partial class gpTemplateWebDO : baseEntity {
        
        private string adtCoIdField;
        
        private string adtIdField;
        
        private System.DateTime adtTimeField;
        
        private bool adtTimeFieldSpecified;
        
        private int fileMakeStateField;
        
        private bool fileMakeStateFieldSpecified;
        
        private string fileUrlField;
        
        private string gtCodeField;
        
        private string gtContentField;
        
        private string gtFileNameField;
        
        private long gtFileSizeField;
        
        private bool gtFileSizeFieldSpecified;
        
        private string gtFileSuffixField;
        
        private int gtGroupField;
        
        private bool gtGroupFieldSpecified;
        
        private string gtGroupNameField;
        
        private string gtIdField;
        
        private string gtNameField;
        
        private int gtTypeField;
        
        private bool gtTypeFieldSpecified;
        
        private string gtTypeNameField;
        
        private string optCoIdField;
        
        private string optIdField;
        
        private System.DateTime optTimeField;
        
        private bool optTimeFieldSpecified;
        
        private string remarkField;
        
        private int sortField;
        
        private bool sortFieldSpecified;
        
        private int stateField;
        
        private bool stateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string adtCoId {
            get {
                return this.adtCoIdField;
            }
            set {
                this.adtCoIdField = value;
                this.RaisePropertyChanged("adtCoId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string adtId {
            get {
                return this.adtIdField;
            }
            set {
                this.adtIdField = value;
                this.RaisePropertyChanged("adtId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime adtTime {
            get {
                return this.adtTimeField;
            }
            set {
                this.adtTimeField = value;
                this.RaisePropertyChanged("adtTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool adtTimeSpecified {
            get {
                return this.adtTimeFieldSpecified;
            }
            set {
                this.adtTimeFieldSpecified = value;
                this.RaisePropertyChanged("adtTimeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int fileMakeState {
            get {
                return this.fileMakeStateField;
            }
            set {
                this.fileMakeStateField = value;
                this.RaisePropertyChanged("fileMakeState");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fileMakeStateSpecified {
            get {
                return this.fileMakeStateFieldSpecified;
            }
            set {
                this.fileMakeStateFieldSpecified = value;
                this.RaisePropertyChanged("fileMakeStateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string fileUrl {
            get {
                return this.fileUrlField;
            }
            set {
                this.fileUrlField = value;
                this.RaisePropertyChanged("fileUrl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string gtCode {
            get {
                return this.gtCodeField;
            }
            set {
                this.gtCodeField = value;
                this.RaisePropertyChanged("gtCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string gtContent {
            get {
                return this.gtContentField;
            }
            set {
                this.gtContentField = value;
                this.RaisePropertyChanged("gtContent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string gtFileName {
            get {
                return this.gtFileNameField;
            }
            set {
                this.gtFileNameField = value;
                this.RaisePropertyChanged("gtFileName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public long gtFileSize {
            get {
                return this.gtFileSizeField;
            }
            set {
                this.gtFileSizeField = value;
                this.RaisePropertyChanged("gtFileSize");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool gtFileSizeSpecified {
            get {
                return this.gtFileSizeFieldSpecified;
            }
            set {
                this.gtFileSizeFieldSpecified = value;
                this.RaisePropertyChanged("gtFileSizeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string gtFileSuffix {
            get {
                return this.gtFileSuffixField;
            }
            set {
                this.gtFileSuffixField = value;
                this.RaisePropertyChanged("gtFileSuffix");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public int gtGroup {
            get {
                return this.gtGroupField;
            }
            set {
                this.gtGroupField = value;
                this.RaisePropertyChanged("gtGroup");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool gtGroupSpecified {
            get {
                return this.gtGroupFieldSpecified;
            }
            set {
                this.gtGroupFieldSpecified = value;
                this.RaisePropertyChanged("gtGroupSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string gtGroupName {
            get {
                return this.gtGroupNameField;
            }
            set {
                this.gtGroupNameField = value;
                this.RaisePropertyChanged("gtGroupName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string gtId {
            get {
                return this.gtIdField;
            }
            set {
                this.gtIdField = value;
                this.RaisePropertyChanged("gtId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string gtName {
            get {
                return this.gtNameField;
            }
            set {
                this.gtNameField = value;
                this.RaisePropertyChanged("gtName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public int gtType {
            get {
                return this.gtTypeField;
            }
            set {
                this.gtTypeField = value;
                this.RaisePropertyChanged("gtType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool gtTypeSpecified {
            get {
                return this.gtTypeFieldSpecified;
            }
            set {
                this.gtTypeFieldSpecified = value;
                this.RaisePropertyChanged("gtTypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string gtTypeName {
            get {
                return this.gtTypeNameField;
            }
            set {
                this.gtTypeNameField = value;
                this.RaisePropertyChanged("gtTypeName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string optCoId {
            get {
                return this.optCoIdField;
            }
            set {
                this.optCoIdField = value;
                this.RaisePropertyChanged("optCoId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string optId {
            get {
                return this.optIdField;
            }
            set {
                this.optIdField = value;
                this.RaisePropertyChanged("optId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public System.DateTime optTime {
            get {
                return this.optTimeField;
            }
            set {
                this.optTimeField = value;
                this.RaisePropertyChanged("optTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool optTimeSpecified {
            get {
                return this.optTimeFieldSpecified;
            }
            set {
                this.optTimeFieldSpecified = value;
                this.RaisePropertyChanged("optTimeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
                this.RaisePropertyChanged("remark");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public int sort {
            get {
                return this.sortField;
            }
            set {
                this.sortField = value;
                this.RaisePropertyChanged("sort");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sortSpecified {
            get {
                return this.sortFieldSpecified;
            }
            set {
                this.sortFieldSpecified = value;
                this.RaisePropertyChanged("sortSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public int state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
                this.RaisePropertyChanged("state");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool stateSpecified {
            get {
                return this.stateFieldSpecified;
            }
            set {
                this.stateFieldSpecified = value;
                this.RaisePropertyChanged("stateSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(gpTemplateWebDO))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.govpurchase.opensource.com/")]
    public abstract partial class baseEntity : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.govpurchase.opensource.com/")]
    public partial class uploadFileResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private resultDO returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public resultDO @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.govpurchase.opensource.com/")]
    public partial class uploadFile : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string gtIdField;
        
        private string buIdField;
        
        private string gtFileNameField;
        
        private string gtFileSuffixField;
        
        private long gtFileSizeField;
        
        private bool gtFileSizeFieldSpecified;
        
        private byte[] gtFileContentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string gtId {
            get {
                return this.gtIdField;
            }
            set {
                this.gtIdField = value;
                this.RaisePropertyChanged("gtId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string buId {
            get {
                return this.buIdField;
            }
            set {
                this.buIdField = value;
                this.RaisePropertyChanged("buId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string gtFileName {
            get {
                return this.gtFileNameField;
            }
            set {
                this.gtFileNameField = value;
                this.RaisePropertyChanged("gtFileName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string gtFileSuffix {
            get {
                return this.gtFileSuffixField;
            }
            set {
                this.gtFileSuffixField = value;
                this.RaisePropertyChanged("gtFileSuffix");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public long gtFileSize {
            get {
                return this.gtFileSizeField;
            }
            set {
                this.gtFileSizeField = value;
                this.RaisePropertyChanged("gtFileSize");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool gtFileSizeSpecified {
            get {
                return this.gtFileSizeFieldSpecified;
            }
            set {
                this.gtFileSizeFieldSpecified = value;
                this.RaisePropertyChanged("gtFileSizeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=5)]
        public byte[] gtFileContent {
            get {
                return this.gtFileContentField;
            }
            set {
                this.gtFileContentField = value;
                this.RaisePropertyChanged("gtFileContent");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.govpurchase.opensource.com/")]
    public partial class addResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private resultDO returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public resultDO @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.govpurchase.opensource.com/")]
    public partial class add : object, System.ComponentModel.INotifyPropertyChanged {
        
        private gpTemplateWebDO gpTemplateWebDOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public gpTemplateWebDO GpTemplateWebDO {
            get {
                return this.gpTemplateWebDOField;
            }
            set {
                this.gpTemplateWebDOField = value;
                this.RaisePropertyChanged("GpTemplateWebDO");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.govpurchase.opensource.com/")]
    public partial class removeResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private resultDO returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public resultDO @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.govpurchase.opensource.com/")]
    public partial class remove : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string gtIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string gtId {
            get {
                return this.gtIdField;
            }
            set {
                this.gtIdField = value;
                this.RaisePropertyChanged("gtId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.govpurchase.opensource.com/")]
    public partial class downLoadFileResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private resultDO returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public resultDO @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.govpurchase.opensource.com/")]
    public partial class downLoadFile : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string gtIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string gtId {
            get {
                return this.gtIdField;
            }
            set {
                this.gtIdField = value;
                this.RaisePropertyChanged("gtId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservice.govpurchase.opensource.com/", ConfigurationName="ServiceReferenceGpTemplate.GpTemplateWebService")]
    public interface GpTemplateWebService {
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Summer.CompetitiveTender.Service.ServiceReferenceGpTemplate.IOException), Action="", Name="IOException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findListResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findList))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getByIdResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getById))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(editResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(edit))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(uploadFileResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(uploadFile))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(addResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(add))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(removeResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(remove))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseEntity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(downLoadFileResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(downLoadFile))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Summer.CompetitiveTender.Service.ServiceReferenceGpTemplate.downLoadFileResponse1 downLoadFile(Summer.CompetitiveTender.Service.ServiceReferenceGpTemplate.downLoadFile1 request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findListResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findList))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getByIdResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getById))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(editResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(edit))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(uploadFileResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(uploadFile))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(addResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(add))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(removeResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(remove))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseEntity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(downLoadFileResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(downLoadFile))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Summer.CompetitiveTender.Service.ServiceReferenceGpTemplate.removeResponse1 remove(Summer.CompetitiveTender.Service.ServiceReferenceGpTemplate.remove1 request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findListResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findList))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getByIdResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getById))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(editResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(edit))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(uploadFileResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(uploadFile))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(addResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(add))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(removeResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(remove))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseEntity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(downLoadFileResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(downLoadFile))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Summer.CompetitiveTender.Service.ServiceReferenceGpTemplate.addResponse1 add(Summer.CompetitiveTender.Service.ServiceReferenceGpTemplate.add1 request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Summer.CompetitiveTender.Service.ServiceReferenceGpTemplate.IOException), Action="", Name="IOException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findListResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findList))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getByIdResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getById))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(editResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(edit))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(uploadFileResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(uploadFile))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(addResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(add))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(removeResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(remove))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseEntity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(downLoadFileResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(downLoadFile))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Summer.CompetitiveTender.Service.ServiceReferenceGpTemplate.uploadFileResponse1 uploadFile(Summer.CompetitiveTender.Service.ServiceReferenceGpTemplate.uploadFile1 request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findListResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findList))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getByIdResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getById))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(editResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(edit))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(uploadFileResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(uploadFile))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(addResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(add))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(removeResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(remove))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseEntity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(downLoadFileResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(downLoadFile))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Summer.CompetitiveTender.Service.ServiceReferenceGpTemplate.editResponse1 edit(Summer.CompetitiveTender.Service.ServiceReferenceGpTemplate.edit1 request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findListResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findList))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getByIdResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getById))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(editResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(edit))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(uploadFileResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(uploadFile))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(addResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(add))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(removeResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(remove))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseEntity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(downLoadFileResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(downLoadFile))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Summer.CompetitiveTender.Service.ServiceReferenceGpTemplate.getByIdResponse1 getById(Summer.CompetitiveTender.Service.ServiceReferenceGpTemplate.getById1 request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findListResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findList))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getByIdResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getById))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(editResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(edit))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(uploadFileResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(uploadFile))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(addResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(add))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(removeResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(remove))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseEntity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(downLoadFileResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(downLoadFile))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Summer.CompetitiveTender.Service.ServiceReferenceGpTemplate.findListResponse1 findList(Summer.CompetitiveTender.Service.ServiceReferenceGpTemplate.findList1 request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="downLoadFile", WrapperNamespace="http://webservice.govpurchase.opensource.com/", IsWrapped=true)]
    public partial class downLoadFile1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.govpurchase.opensource.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string gtId;
        
        public downLoadFile1() {
        }
        
        public downLoadFile1(string gtId) {
            this.gtId = gtId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="downLoadFileResponse", WrapperNamespace="http://webservice.govpurchase.opensource.com/", IsWrapped=true)]
    public partial class downLoadFileResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.govpurchase.opensource.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Summer.CompetitiveTender.Service.ServiceReferenceGpTemplate.resultDO @return;
        
        public downLoadFileResponse1() {
        }
        
        public downLoadFileResponse1(Summer.CompetitiveTender.Service.ServiceReferenceGpTemplate.resultDO @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="remove", WrapperNamespace="http://webservice.govpurchase.opensource.com/", IsWrapped=true)]
    public partial class remove1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.govpurchase.opensource.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string gtId;
        
        public remove1() {
        }
        
        public remove1(string gtId) {
            this.gtId = gtId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="removeResponse", WrapperNamespace="http://webservice.govpurchase.opensource.com/", IsWrapped=true)]
    public partial class removeResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.govpurchase.opensource.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Summer.CompetitiveTender.Service.ServiceReferenceGpTemplate.resultDO @return;
        
        public removeResponse1() {
        }
        
        public removeResponse1(Summer.CompetitiveTender.Service.ServiceReferenceGpTemplate.resultDO @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="add", WrapperNamespace="http://webservice.govpurchase.opensource.com/", IsWrapped=true)]
    public partial class add1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.govpurchase.opensource.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Summer.CompetitiveTender.Service.ServiceReferenceGpTemplate.gpTemplateWebDO GpTemplateWebDO;
        
        public add1() {
        }
        
        public add1(Summer.CompetitiveTender.Service.ServiceReferenceGpTemplate.gpTemplateWebDO GpTemplateWebDO) {
            this.GpTemplateWebDO = GpTemplateWebDO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addResponse", WrapperNamespace="http://webservice.govpurchase.opensource.com/", IsWrapped=true)]
    public partial class addResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.govpurchase.opensource.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Summer.CompetitiveTender.Service.ServiceReferenceGpTemplate.resultDO @return;
        
        public addResponse1() {
        }
        
        public addResponse1(Summer.CompetitiveTender.Service.ServiceReferenceGpTemplate.resultDO @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="uploadFile", WrapperNamespace="http://webservice.govpurchase.opensource.com/", IsWrapped=true)]
    public partial class uploadFile1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.govpurchase.opensource.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string gtId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.govpurchase.opensource.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string buId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.govpurchase.opensource.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string gtFileName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.govpurchase.opensource.com/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string gtFileSuffix;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.govpurchase.opensource.com/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long gtFileSize;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.govpurchase.opensource.com/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary")]
        public byte[] gtFileContent;
        
        public uploadFile1() {
        }
        
        public uploadFile1(string gtId, string buId, string gtFileName, string gtFileSuffix, long gtFileSize, byte[] gtFileContent) {
            this.gtId = gtId;
            this.buId = buId;
            this.gtFileName = gtFileName;
            this.gtFileSuffix = gtFileSuffix;
            this.gtFileSize = gtFileSize;
            this.gtFileContent = gtFileContent;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="uploadFileResponse", WrapperNamespace="http://webservice.govpurchase.opensource.com/", IsWrapped=true)]
    public partial class uploadFileResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.govpurchase.opensource.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Summer.CompetitiveTender.Service.ServiceReferenceGpTemplate.resultDO @return;
        
        public uploadFileResponse1() {
        }
        
        public uploadFileResponse1(Summer.CompetitiveTender.Service.ServiceReferenceGpTemplate.resultDO @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="edit", WrapperNamespace="http://webservice.govpurchase.opensource.com/", IsWrapped=true)]
    public partial class edit1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.govpurchase.opensource.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Summer.CompetitiveTender.Service.ServiceReferenceGpTemplate.gpTemplateWebDO GpTemplateWebDO;
        
        public edit1() {
        }
        
        public edit1(Summer.CompetitiveTender.Service.ServiceReferenceGpTemplate.gpTemplateWebDO GpTemplateWebDO) {
            this.GpTemplateWebDO = GpTemplateWebDO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="editResponse", WrapperNamespace="http://webservice.govpurchase.opensource.com/", IsWrapped=true)]
    public partial class editResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.govpurchase.opensource.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Summer.CompetitiveTender.Service.ServiceReferenceGpTemplate.resultDO @return;
        
        public editResponse1() {
        }
        
        public editResponse1(Summer.CompetitiveTender.Service.ServiceReferenceGpTemplate.resultDO @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getById", WrapperNamespace="http://webservice.govpurchase.opensource.com/", IsWrapped=true)]
    public partial class getById1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.govpurchase.opensource.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string gtId;
        
        public getById1() {
        }
        
        public getById1(string gtId) {
            this.gtId = gtId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getByIdResponse", WrapperNamespace="http://webservice.govpurchase.opensource.com/", IsWrapped=true)]
    public partial class getByIdResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.govpurchase.opensource.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Summer.CompetitiveTender.Service.ServiceReferenceGpTemplate.resultDO @return;
        
        public getByIdResponse1() {
        }
        
        public getByIdResponse1(Summer.CompetitiveTender.Service.ServiceReferenceGpTemplate.resultDO @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findList", WrapperNamespace="http://webservice.govpurchase.opensource.com/", IsWrapped=true)]
    public partial class findList1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.govpurchase.opensource.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string auID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.govpurchase.opensource.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string gtName;
        
        public findList1() {
        }
        
        public findList1(string auID, string gtName) {
            this.auID = auID;
            this.gtName = gtName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findListResponse", WrapperNamespace="http://webservice.govpurchase.opensource.com/", IsWrapped=true)]
    public partial class findListResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.govpurchase.opensource.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Summer.CompetitiveTender.Service.ServiceReferenceGpTemplate.resultDO @return;
        
        public findListResponse1() {
        }
        
        public findListResponse1(Summer.CompetitiveTender.Service.ServiceReferenceGpTemplate.resultDO @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GpTemplateWebServiceChannel : Summer.CompetitiveTender.Service.ServiceReferenceGpTemplate.GpTemplateWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GpTemplateWebServiceClient : System.ServiceModel.ClientBase<Summer.CompetitiveTender.Service.ServiceReferenceGpTemplate.GpTemplateWebService>, Summer.CompetitiveTender.Service.ServiceReferenceGpTemplate.GpTemplateWebService {
        
        public GpTemplateWebServiceClient() {
        }
        
        public GpTemplateWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GpTemplateWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GpTemplateWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GpTemplateWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Summer.CompetitiveTender.Service.ServiceReferenceGpTemplate.downLoadFileResponse1 Summer.CompetitiveTender.Service.ServiceReferenceGpTemplate.GpTemplateWebService.downLoadFile(Summer.CompetitiveTender.Service.ServiceReferenceGpTemplate.downLoadFile1 request) {
            return base.Channel.downLoadFile(request);
        }
        
        public Summer.CompetitiveTender.Service.ServiceReferenceGpTemplate.resultDO downLoadFile(string gtId) {
            Summer.CompetitiveTender.Service.ServiceReferenceGpTemplate.downLoadFile1 inValue = new Summer.CompetitiveTender.Service.ServiceReferenceGpTemplate.downLoadFile1();
            inValue.gtId = gtId;
            Summer.CompetitiveTender.Service.ServiceReferenceGpTemplate.downLoadFileResponse1 retVal = ((Summer.CompetitiveTender.Service.ServiceReferenceGpTemplate.GpTemplateWebService)(this)).downLoadFile(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Summer.CompetitiveTender.Service.ServiceReferenceGpTemplate.removeResponse1 Summer.CompetitiveTender.Service.ServiceReferenceGpTemplate.GpTemplateWebService.remove(Summer.CompetitiveTender.Service.ServiceReferenceGpTemplate.remove1 request) {
            return base.Channel.remove(request);
        }
        
        public Summer.CompetitiveTender.Service.ServiceReferenceGpTemplate.resultDO remove(string gtId) {
            Summer.CompetitiveTender.Service.ServiceReferenceGpTemplate.remove1 inValue = new Summer.CompetitiveTender.Service.ServiceReferenceGpTemplate.remove1();
            inValue.gtId = gtId;
            Summer.CompetitiveTender.Service.ServiceReferenceGpTemplate.removeResponse1 retVal = ((Summer.CompetitiveTender.Service.ServiceReferenceGpTemplate.GpTemplateWebService)(this)).remove(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Summer.CompetitiveTender.Service.ServiceReferenceGpTemplate.addResponse1 Summer.CompetitiveTender.Service.ServiceReferenceGpTemplate.GpTemplateWebService.add(Summer.CompetitiveTender.Service.ServiceReferenceGpTemplate.add1 request) {
            return base.Channel.add(request);
        }
        
        public Summer.CompetitiveTender.Service.ServiceReferenceGpTemplate.resultDO add(Summer.CompetitiveTender.Service.ServiceReferenceGpTemplate.gpTemplateWebDO GpTemplateWebDO) {
            Summer.CompetitiveTender.Service.ServiceReferenceGpTemplate.add1 inValue = new Summer.CompetitiveTender.Service.ServiceReferenceGpTemplate.add1();
            inValue.GpTemplateWebDO = GpTemplateWebDO;
            Summer.CompetitiveTender.Service.ServiceReferenceGpTemplate.addResponse1 retVal = ((Summer.CompetitiveTender.Service.ServiceReferenceGpTemplate.GpTemplateWebService)(this)).add(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Summer.CompetitiveTender.Service.ServiceReferenceGpTemplate.uploadFileResponse1 Summer.CompetitiveTender.Service.ServiceReferenceGpTemplate.GpTemplateWebService.uploadFile(Summer.CompetitiveTender.Service.ServiceReferenceGpTemplate.uploadFile1 request) {
            return base.Channel.uploadFile(request);
        }
        
        public Summer.CompetitiveTender.Service.ServiceReferenceGpTemplate.resultDO uploadFile(string gtId, string buId, string gtFileName, string gtFileSuffix, long gtFileSize, byte[] gtFileContent) {
            Summer.CompetitiveTender.Service.ServiceReferenceGpTemplate.uploadFile1 inValue = new Summer.CompetitiveTender.Service.ServiceReferenceGpTemplate.uploadFile1();
            inValue.gtId = gtId;
            inValue.buId = buId;
            inValue.gtFileName = gtFileName;
            inValue.gtFileSuffix = gtFileSuffix;
            inValue.gtFileSize = gtFileSize;
            inValue.gtFileContent = gtFileContent;
            Summer.CompetitiveTender.Service.ServiceReferenceGpTemplate.uploadFileResponse1 retVal = ((Summer.CompetitiveTender.Service.ServiceReferenceGpTemplate.GpTemplateWebService)(this)).uploadFile(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Summer.CompetitiveTender.Service.ServiceReferenceGpTemplate.editResponse1 Summer.CompetitiveTender.Service.ServiceReferenceGpTemplate.GpTemplateWebService.edit(Summer.CompetitiveTender.Service.ServiceReferenceGpTemplate.edit1 request) {
            return base.Channel.edit(request);
        }
        
        public Summer.CompetitiveTender.Service.ServiceReferenceGpTemplate.resultDO edit(Summer.CompetitiveTender.Service.ServiceReferenceGpTemplate.gpTemplateWebDO GpTemplateWebDO) {
            Summer.CompetitiveTender.Service.ServiceReferenceGpTemplate.edit1 inValue = new Summer.CompetitiveTender.Service.ServiceReferenceGpTemplate.edit1();
            inValue.GpTemplateWebDO = GpTemplateWebDO;
            Summer.CompetitiveTender.Service.ServiceReferenceGpTemplate.editResponse1 retVal = ((Summer.CompetitiveTender.Service.ServiceReferenceGpTemplate.GpTemplateWebService)(this)).edit(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Summer.CompetitiveTender.Service.ServiceReferenceGpTemplate.getByIdResponse1 Summer.CompetitiveTender.Service.ServiceReferenceGpTemplate.GpTemplateWebService.getById(Summer.CompetitiveTender.Service.ServiceReferenceGpTemplate.getById1 request) {
            return base.Channel.getById(request);
        }
        
        public Summer.CompetitiveTender.Service.ServiceReferenceGpTemplate.resultDO getById(string gtId) {
            Summer.CompetitiveTender.Service.ServiceReferenceGpTemplate.getById1 inValue = new Summer.CompetitiveTender.Service.ServiceReferenceGpTemplate.getById1();
            inValue.gtId = gtId;
            Summer.CompetitiveTender.Service.ServiceReferenceGpTemplate.getByIdResponse1 retVal = ((Summer.CompetitiveTender.Service.ServiceReferenceGpTemplate.GpTemplateWebService)(this)).getById(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Summer.CompetitiveTender.Service.ServiceReferenceGpTemplate.findListResponse1 Summer.CompetitiveTender.Service.ServiceReferenceGpTemplate.GpTemplateWebService.findList(Summer.CompetitiveTender.Service.ServiceReferenceGpTemplate.findList1 request) {
            return base.Channel.findList(request);
        }
        
        public Summer.CompetitiveTender.Service.ServiceReferenceGpTemplate.resultDO findList(string auID, string gtName) {
            Summer.CompetitiveTender.Service.ServiceReferenceGpTemplate.findList1 inValue = new Summer.CompetitiveTender.Service.ServiceReferenceGpTemplate.findList1();
            inValue.auID = auID;
            inValue.gtName = gtName;
            Summer.CompetitiveTender.Service.ServiceReferenceGpTemplate.findListResponse1 retVal = ((Summer.CompetitiveTender.Service.ServiceReferenceGpTemplate.GpTemplateWebService)(this)).findList(inValue);
            return retVal.@return;
        }
    }
}
