//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Summer.CompetitiveTender.Service.ServiceReferenceGpTenderEvalEle {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservice.govpurchase.opensource.com/", ConfigurationName="ServiceReferenceGpTenderEvalEle.GpTenderEvalEleWebService")]
    public interface GpTenderEvalEleWebService {
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(removeResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(remove))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getByIdResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getById))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findAllResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findAll))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(editResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(edit))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(saveResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(save))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseEntity))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Summer.CompetitiveTender.Service.ServiceReferenceGpTenderEvalEle.saveResponse1 save(Summer.CompetitiveTender.Service.ServiceReferenceGpTenderEvalEle.save1 request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(removeResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(remove))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getByIdResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getById))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findAllResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findAll))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(editResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(edit))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(saveResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(save))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseEntity))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Summer.CompetitiveTender.Service.ServiceReferenceGpTenderEvalEle.editResponse1 edit(Summer.CompetitiveTender.Service.ServiceReferenceGpTenderEvalEle.edit1 request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(removeResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(remove))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getByIdResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getById))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findAllResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findAll))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(editResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(edit))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(saveResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(save))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseEntity))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Summer.CompetitiveTender.Service.ServiceReferenceGpTenderEvalEle.findAllResponse1 findAll(Summer.CompetitiveTender.Service.ServiceReferenceGpTenderEvalEle.findAll1 request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(removeResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(remove))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getByIdResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getById))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findAllResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findAll))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(editResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(edit))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(saveResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(save))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseEntity))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Summer.CompetitiveTender.Service.ServiceReferenceGpTenderEvalEle.getByIdResponse1 getById(Summer.CompetitiveTender.Service.ServiceReferenceGpTenderEvalEle.getById1 request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(removeResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(remove))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getByIdResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getById))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findAllResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findAll))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(editResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(edit))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(saveResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(save))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseEntity))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Summer.CompetitiveTender.Service.ServiceReferenceGpTenderEvalEle.removeResponse1 remove(Summer.CompetitiveTender.Service.ServiceReferenceGpTenderEvalEle.remove1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.govpurchase.opensource.com/")]
    public partial class gpTenderEvalEleWebDO : baseEntity {
        
        private string adtCoIdField;
        
        private string adtIdField;
        
        private System.DateTime adtTimeField;
        
        private bool adtTimeFieldSpecified;
        
        private int canDelField;
        
        private bool canDelFieldSpecified;
        
        private decimal evalGradsField;
        
        private bool evalGradsFieldSpecified;
        
        private decimal evalNumField;
        
        private bool evalNumFieldSpecified;
        
        private string evalUnitField;
        
        private string gewigIdField;
        
        private string gewigNameField;
        
        private decimal greatNumField;
        
        private bool greatNumFieldSpecified;
        
        private int greatWayField;
        
        private bool greatWayFieldSpecified;
        
        private string gsIdField;
        
        private string gteeCodeField;
        
        private string gteeIdField;
        
        private string gteeNameField;
        
        private string gtpIdField;
        
        private decimal littleNumField;
        
        private bool littleNumFieldSpecified;
        
        private int littleWayField;
        
        private bool littleWayFieldSpecified;
        
        private decimal maxScoreField;
        
        private bool maxScoreFieldSpecified;
        
        private decimal minScoreField;
        
        private bool minScoreFieldSpecified;
        
        private string optCoIdField;
        
        private string optIdField;
        
        private System.DateTime optTimeField;
        
        private bool optTimeFieldSpecified;
        
        private decimal standardField;
        
        private bool standardFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string adtCoId {
            get {
                return this.adtCoIdField;
            }
            set {
                this.adtCoIdField = value;
                this.RaisePropertyChanged("adtCoId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string adtId {
            get {
                return this.adtIdField;
            }
            set {
                this.adtIdField = value;
                this.RaisePropertyChanged("adtId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime adtTime {
            get {
                return this.adtTimeField;
            }
            set {
                this.adtTimeField = value;
                this.RaisePropertyChanged("adtTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool adtTimeSpecified {
            get {
                return this.adtTimeFieldSpecified;
            }
            set {
                this.adtTimeFieldSpecified = value;
                this.RaisePropertyChanged("adtTimeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int canDel {
            get {
                return this.canDelField;
            }
            set {
                this.canDelField = value;
                this.RaisePropertyChanged("canDel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool canDelSpecified {
            get {
                return this.canDelFieldSpecified;
            }
            set {
                this.canDelFieldSpecified = value;
                this.RaisePropertyChanged("canDelSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public decimal evalGrads {
            get {
                return this.evalGradsField;
            }
            set {
                this.evalGradsField = value;
                this.RaisePropertyChanged("evalGrads");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool evalGradsSpecified {
            get {
                return this.evalGradsFieldSpecified;
            }
            set {
                this.evalGradsFieldSpecified = value;
                this.RaisePropertyChanged("evalGradsSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public decimal evalNum {
            get {
                return this.evalNumField;
            }
            set {
                this.evalNumField = value;
                this.RaisePropertyChanged("evalNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool evalNumSpecified {
            get {
                return this.evalNumFieldSpecified;
            }
            set {
                this.evalNumFieldSpecified = value;
                this.RaisePropertyChanged("evalNumSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string evalUnit {
            get {
                return this.evalUnitField;
            }
            set {
                this.evalUnitField = value;
                this.RaisePropertyChanged("evalUnit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string gewigId {
            get {
                return this.gewigIdField;
            }
            set {
                this.gewigIdField = value;
                this.RaisePropertyChanged("gewigId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string gewigName {
            get {
                return this.gewigNameField;
            }
            set {
                this.gewigNameField = value;
                this.RaisePropertyChanged("gewigName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public decimal greatNum {
            get {
                return this.greatNumField;
            }
            set {
                this.greatNumField = value;
                this.RaisePropertyChanged("greatNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool greatNumSpecified {
            get {
                return this.greatNumFieldSpecified;
            }
            set {
                this.greatNumFieldSpecified = value;
                this.RaisePropertyChanged("greatNumSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public int greatWay {
            get {
                return this.greatWayField;
            }
            set {
                this.greatWayField = value;
                this.RaisePropertyChanged("greatWay");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool greatWaySpecified {
            get {
                return this.greatWayFieldSpecified;
            }
            set {
                this.greatWayFieldSpecified = value;
                this.RaisePropertyChanged("greatWaySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string gsId {
            get {
                return this.gsIdField;
            }
            set {
                this.gsIdField = value;
                this.RaisePropertyChanged("gsId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string gteeCode {
            get {
                return this.gteeCodeField;
            }
            set {
                this.gteeCodeField = value;
                this.RaisePropertyChanged("gteeCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string gteeId {
            get {
                return this.gteeIdField;
            }
            set {
                this.gteeIdField = value;
                this.RaisePropertyChanged("gteeId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string gteeName {
            get {
                return this.gteeNameField;
            }
            set {
                this.gteeNameField = value;
                this.RaisePropertyChanged("gteeName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string gtpId {
            get {
                return this.gtpIdField;
            }
            set {
                this.gtpIdField = value;
                this.RaisePropertyChanged("gtpId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public decimal littleNum {
            get {
                return this.littleNumField;
            }
            set {
                this.littleNumField = value;
                this.RaisePropertyChanged("littleNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool littleNumSpecified {
            get {
                return this.littleNumFieldSpecified;
            }
            set {
                this.littleNumFieldSpecified = value;
                this.RaisePropertyChanged("littleNumSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public int littleWay {
            get {
                return this.littleWayField;
            }
            set {
                this.littleWayField = value;
                this.RaisePropertyChanged("littleWay");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool littleWaySpecified {
            get {
                return this.littleWayFieldSpecified;
            }
            set {
                this.littleWayFieldSpecified = value;
                this.RaisePropertyChanged("littleWaySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public decimal maxScore {
            get {
                return this.maxScoreField;
            }
            set {
                this.maxScoreField = value;
                this.RaisePropertyChanged("maxScore");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maxScoreSpecified {
            get {
                return this.maxScoreFieldSpecified;
            }
            set {
                this.maxScoreFieldSpecified = value;
                this.RaisePropertyChanged("maxScoreSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public decimal minScore {
            get {
                return this.minScoreField;
            }
            set {
                this.minScoreField = value;
                this.RaisePropertyChanged("minScore");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool minScoreSpecified {
            get {
                return this.minScoreFieldSpecified;
            }
            set {
                this.minScoreFieldSpecified = value;
                this.RaisePropertyChanged("minScoreSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string optCoId {
            get {
                return this.optCoIdField;
            }
            set {
                this.optCoIdField = value;
                this.RaisePropertyChanged("optCoId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string optId {
            get {
                return this.optIdField;
            }
            set {
                this.optIdField = value;
                this.RaisePropertyChanged("optId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public System.DateTime optTime {
            get {
                return this.optTimeField;
            }
            set {
                this.optTimeField = value;
                this.RaisePropertyChanged("optTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool optTimeSpecified {
            get {
                return this.optTimeFieldSpecified;
            }
            set {
                this.optTimeFieldSpecified = value;
                this.RaisePropertyChanged("optTimeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public decimal standard {
            get {
                return this.standardField;
            }
            set {
                this.standardField = value;
                this.RaisePropertyChanged("standard");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool standardSpecified {
            get {
                return this.standardFieldSpecified;
            }
            set {
                this.standardFieldSpecified = value;
                this.RaisePropertyChanged("standardSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(gpTenderEvalEleWebDO))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.govpurchase.opensource.com/")]
    public abstract partial class baseEntity : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.govpurchase.opensource.com/")]
    public partial class removeResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private resultDO returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public resultDO @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.govpurchase.opensource.com/")]
    public partial class resultDO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codeField;
        
        private byte[] fileContentField;
        
        private string messageField;
        
        private object objField;
        
        private object[] objListField;
        
        private bool successField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=1)]
        public byte[] fileContent {
            get {
                return this.fileContentField;
            }
            set {
                this.fileContentField = value;
                this.RaisePropertyChanged("fileContent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public object obj {
            get {
                return this.objField;
            }
            set {
                this.objField = value;
                this.RaisePropertyChanged("obj");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("objList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public object[] objList {
            get {
                return this.objListField;
            }
            set {
                this.objListField = value;
                this.RaisePropertyChanged("objList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public bool success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
                this.RaisePropertyChanged("success");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.govpurchase.opensource.com/")]
    public partial class remove : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string gteeIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string gteeId {
            get {
                return this.gteeIdField;
            }
            set {
                this.gteeIdField = value;
                this.RaisePropertyChanged("gteeId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.govpurchase.opensource.com/")]
    public partial class getByIdResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private resultDO returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public resultDO @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.govpurchase.opensource.com/")]
    public partial class getById : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string gteeIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string gteeId {
            get {
                return this.gteeIdField;
            }
            set {
                this.gteeIdField = value;
                this.RaisePropertyChanged("gteeId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.govpurchase.opensource.com/")]
    public partial class findAllResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private resultDO returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public resultDO @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.govpurchase.opensource.com/")]
    public partial class findAll : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string gsIdField;
        
        private string gteeNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string gsId {
            get {
                return this.gsIdField;
            }
            set {
                this.gsIdField = value;
                this.RaisePropertyChanged("gsId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string gteeName {
            get {
                return this.gteeNameField;
            }
            set {
                this.gteeNameField = value;
                this.RaisePropertyChanged("gteeName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.govpurchase.opensource.com/")]
    public partial class editResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private resultDO returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public resultDO @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.govpurchase.opensource.com/")]
    public partial class edit : object, System.ComponentModel.INotifyPropertyChanged {
        
        private gpTenderEvalEleWebDO gpTenderEvalEleWebDOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public gpTenderEvalEleWebDO GpTenderEvalEleWebDO {
            get {
                return this.gpTenderEvalEleWebDOField;
            }
            set {
                this.gpTenderEvalEleWebDOField = value;
                this.RaisePropertyChanged("GpTenderEvalEleWebDO");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.govpurchase.opensource.com/")]
    public partial class saveResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private resultDO returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public resultDO @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.govpurchase.opensource.com/")]
    public partial class save : object, System.ComponentModel.INotifyPropertyChanged {
        
        private gpTenderEvalEleWebDO gpTenderEvalEleWebDOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public gpTenderEvalEleWebDO GpTenderEvalEleWebDO {
            get {
                return this.gpTenderEvalEleWebDOField;
            }
            set {
                this.gpTenderEvalEleWebDOField = value;
                this.RaisePropertyChanged("GpTenderEvalEleWebDO");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="save", WrapperNamespace="http://webservice.govpurchase.opensource.com/", IsWrapped=true)]
    public partial class save1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.govpurchase.opensource.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Summer.CompetitiveTender.Service.ServiceReferenceGpTenderEvalEle.gpTenderEvalEleWebDO GpTenderEvalEleWebDO;
        
        public save1() {
        }
        
        public save1(Summer.CompetitiveTender.Service.ServiceReferenceGpTenderEvalEle.gpTenderEvalEleWebDO GpTenderEvalEleWebDO) {
            this.GpTenderEvalEleWebDO = GpTenderEvalEleWebDO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="saveResponse", WrapperNamespace="http://webservice.govpurchase.opensource.com/", IsWrapped=true)]
    public partial class saveResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.govpurchase.opensource.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Summer.CompetitiveTender.Service.ServiceReferenceGpTenderEvalEle.resultDO @return;
        
        public saveResponse1() {
        }
        
        public saveResponse1(Summer.CompetitiveTender.Service.ServiceReferenceGpTenderEvalEle.resultDO @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="edit", WrapperNamespace="http://webservice.govpurchase.opensource.com/", IsWrapped=true)]
    public partial class edit1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.govpurchase.opensource.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Summer.CompetitiveTender.Service.ServiceReferenceGpTenderEvalEle.gpTenderEvalEleWebDO GpTenderEvalEleWebDO;
        
        public edit1() {
        }
        
        public edit1(Summer.CompetitiveTender.Service.ServiceReferenceGpTenderEvalEle.gpTenderEvalEleWebDO GpTenderEvalEleWebDO) {
            this.GpTenderEvalEleWebDO = GpTenderEvalEleWebDO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="editResponse", WrapperNamespace="http://webservice.govpurchase.opensource.com/", IsWrapped=true)]
    public partial class editResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.govpurchase.opensource.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Summer.CompetitiveTender.Service.ServiceReferenceGpTenderEvalEle.resultDO @return;
        
        public editResponse1() {
        }
        
        public editResponse1(Summer.CompetitiveTender.Service.ServiceReferenceGpTenderEvalEle.resultDO @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findAll", WrapperNamespace="http://webservice.govpurchase.opensource.com/", IsWrapped=true)]
    public partial class findAll1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.govpurchase.opensource.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string gsId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.govpurchase.opensource.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string gteeName;
        
        public findAll1() {
        }
        
        public findAll1(string gsId, string gteeName) {
            this.gsId = gsId;
            this.gteeName = gteeName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findAllResponse", WrapperNamespace="http://webservice.govpurchase.opensource.com/", IsWrapped=true)]
    public partial class findAllResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.govpurchase.opensource.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Summer.CompetitiveTender.Service.ServiceReferenceGpTenderEvalEle.resultDO @return;
        
        public findAllResponse1() {
        }
        
        public findAllResponse1(Summer.CompetitiveTender.Service.ServiceReferenceGpTenderEvalEle.resultDO @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getById", WrapperNamespace="http://webservice.govpurchase.opensource.com/", IsWrapped=true)]
    public partial class getById1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.govpurchase.opensource.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string gteeId;
        
        public getById1() {
        }
        
        public getById1(string gteeId) {
            this.gteeId = gteeId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getByIdResponse", WrapperNamespace="http://webservice.govpurchase.opensource.com/", IsWrapped=true)]
    public partial class getByIdResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.govpurchase.opensource.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Summer.CompetitiveTender.Service.ServiceReferenceGpTenderEvalEle.resultDO @return;
        
        public getByIdResponse1() {
        }
        
        public getByIdResponse1(Summer.CompetitiveTender.Service.ServiceReferenceGpTenderEvalEle.resultDO @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="remove", WrapperNamespace="http://webservice.govpurchase.opensource.com/", IsWrapped=true)]
    public partial class remove1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.govpurchase.opensource.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string gteeId;
        
        public remove1() {
        }
        
        public remove1(string gteeId) {
            this.gteeId = gteeId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="removeResponse", WrapperNamespace="http://webservice.govpurchase.opensource.com/", IsWrapped=true)]
    public partial class removeResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.govpurchase.opensource.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Summer.CompetitiveTender.Service.ServiceReferenceGpTenderEvalEle.resultDO @return;
        
        public removeResponse1() {
        }
        
        public removeResponse1(Summer.CompetitiveTender.Service.ServiceReferenceGpTenderEvalEle.resultDO @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GpTenderEvalEleWebServiceChannel : Summer.CompetitiveTender.Service.ServiceReferenceGpTenderEvalEle.GpTenderEvalEleWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GpTenderEvalEleWebServiceClient : System.ServiceModel.ClientBase<Summer.CompetitiveTender.Service.ServiceReferenceGpTenderEvalEle.GpTenderEvalEleWebService>, Summer.CompetitiveTender.Service.ServiceReferenceGpTenderEvalEle.GpTenderEvalEleWebService {
        
        public GpTenderEvalEleWebServiceClient() {
        }
        
        public GpTenderEvalEleWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GpTenderEvalEleWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GpTenderEvalEleWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GpTenderEvalEleWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Summer.CompetitiveTender.Service.ServiceReferenceGpTenderEvalEle.saveResponse1 Summer.CompetitiveTender.Service.ServiceReferenceGpTenderEvalEle.GpTenderEvalEleWebService.save(Summer.CompetitiveTender.Service.ServiceReferenceGpTenderEvalEle.save1 request) {
            return base.Channel.save(request);
        }
        
        public Summer.CompetitiveTender.Service.ServiceReferenceGpTenderEvalEle.resultDO save(Summer.CompetitiveTender.Service.ServiceReferenceGpTenderEvalEle.gpTenderEvalEleWebDO GpTenderEvalEleWebDO) {
            Summer.CompetitiveTender.Service.ServiceReferenceGpTenderEvalEle.save1 inValue = new Summer.CompetitiveTender.Service.ServiceReferenceGpTenderEvalEle.save1();
            inValue.GpTenderEvalEleWebDO = GpTenderEvalEleWebDO;
            Summer.CompetitiveTender.Service.ServiceReferenceGpTenderEvalEle.saveResponse1 retVal = ((Summer.CompetitiveTender.Service.ServiceReferenceGpTenderEvalEle.GpTenderEvalEleWebService)(this)).save(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Summer.CompetitiveTender.Service.ServiceReferenceGpTenderEvalEle.editResponse1 Summer.CompetitiveTender.Service.ServiceReferenceGpTenderEvalEle.GpTenderEvalEleWebService.edit(Summer.CompetitiveTender.Service.ServiceReferenceGpTenderEvalEle.edit1 request) {
            return base.Channel.edit(request);
        }
        
        public Summer.CompetitiveTender.Service.ServiceReferenceGpTenderEvalEle.resultDO edit(Summer.CompetitiveTender.Service.ServiceReferenceGpTenderEvalEle.gpTenderEvalEleWebDO GpTenderEvalEleWebDO) {
            Summer.CompetitiveTender.Service.ServiceReferenceGpTenderEvalEle.edit1 inValue = new Summer.CompetitiveTender.Service.ServiceReferenceGpTenderEvalEle.edit1();
            inValue.GpTenderEvalEleWebDO = GpTenderEvalEleWebDO;
            Summer.CompetitiveTender.Service.ServiceReferenceGpTenderEvalEle.editResponse1 retVal = ((Summer.CompetitiveTender.Service.ServiceReferenceGpTenderEvalEle.GpTenderEvalEleWebService)(this)).edit(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Summer.CompetitiveTender.Service.ServiceReferenceGpTenderEvalEle.findAllResponse1 Summer.CompetitiveTender.Service.ServiceReferenceGpTenderEvalEle.GpTenderEvalEleWebService.findAll(Summer.CompetitiveTender.Service.ServiceReferenceGpTenderEvalEle.findAll1 request) {
            return base.Channel.findAll(request);
        }
        
        public Summer.CompetitiveTender.Service.ServiceReferenceGpTenderEvalEle.resultDO findAll(string gsId, string gteeName) {
            Summer.CompetitiveTender.Service.ServiceReferenceGpTenderEvalEle.findAll1 inValue = new Summer.CompetitiveTender.Service.ServiceReferenceGpTenderEvalEle.findAll1();
            inValue.gsId = gsId;
            inValue.gteeName = gteeName;
            Summer.CompetitiveTender.Service.ServiceReferenceGpTenderEvalEle.findAllResponse1 retVal = ((Summer.CompetitiveTender.Service.ServiceReferenceGpTenderEvalEle.GpTenderEvalEleWebService)(this)).findAll(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Summer.CompetitiveTender.Service.ServiceReferenceGpTenderEvalEle.getByIdResponse1 Summer.CompetitiveTender.Service.ServiceReferenceGpTenderEvalEle.GpTenderEvalEleWebService.getById(Summer.CompetitiveTender.Service.ServiceReferenceGpTenderEvalEle.getById1 request) {
            return base.Channel.getById(request);
        }
        
        public Summer.CompetitiveTender.Service.ServiceReferenceGpTenderEvalEle.resultDO getById(string gteeId) {
            Summer.CompetitiveTender.Service.ServiceReferenceGpTenderEvalEle.getById1 inValue = new Summer.CompetitiveTender.Service.ServiceReferenceGpTenderEvalEle.getById1();
            inValue.gteeId = gteeId;
            Summer.CompetitiveTender.Service.ServiceReferenceGpTenderEvalEle.getByIdResponse1 retVal = ((Summer.CompetitiveTender.Service.ServiceReferenceGpTenderEvalEle.GpTenderEvalEleWebService)(this)).getById(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Summer.CompetitiveTender.Service.ServiceReferenceGpTenderEvalEle.removeResponse1 Summer.CompetitiveTender.Service.ServiceReferenceGpTenderEvalEle.GpTenderEvalEleWebService.remove(Summer.CompetitiveTender.Service.ServiceReferenceGpTenderEvalEle.remove1 request) {
            return base.Channel.remove(request);
        }
        
        public Summer.CompetitiveTender.Service.ServiceReferenceGpTenderEvalEle.resultDO remove(string gteeId) {
            Summer.CompetitiveTender.Service.ServiceReferenceGpTenderEvalEle.remove1 inValue = new Summer.CompetitiveTender.Service.ServiceReferenceGpTenderEvalEle.remove1();
            inValue.gteeId = gteeId;
            Summer.CompetitiveTender.Service.ServiceReferenceGpTenderEvalEle.removeResponse1 retVal = ((Summer.CompetitiveTender.Service.ServiceReferenceGpTenderEvalEle.GpTenderEvalEleWebService)(this)).remove(inValue);
            return retVal.@return;
        }
    }
}
